import { lesson as l, out, contains, exists, missing, content, ok } from './helpers.mjs';

export default {
  'New-Item': [
    l({ title: 'Create a file with initial content', focus: '-ItemType File and -Value create a usable file in one operation.', example: "New-Item -ItemType File -Path app.conf -Value 'mode=dev'", task: 'Create status.txt containing ready, then print its content.', solution: "New-Item -ItemType File -Path status.txt -Value 'ready' | Out-Null; Get-Content status.txt", checks: [content('status.txt', 'ready'), ...out('ready')] }),
    l({ title: 'Create missing parent directories', focus: '-Force allows New-Item to create a directory path whose parent segments do not yet exist.', example: 'New-Item -ItemType Directory -Path logs\archive -Force', task: 'Create the nested directory project\config\production and print its leaf name.', solution: 'New-Item -ItemType Directory -Path project\config\production -Force | Select-Object -ExpandProperty Name', checks: [exists('project/config/production', 'directory'), ...out('production')] }),
    l({ title: 'Create several related directories', focus: '-Path accepts an array so related items can be created and reviewed together.', example: "New-Item -ItemType Directory -Path 'src','tests'", task: 'Create bin, config, and logs directories in one New-Item call, then print their names sorted.', solution: "New-Item -ItemType Directory -Path 'bin','config','logs' | Sort-Object Name | Select-Object -ExpandProperty Name", checks: [exists('bin', 'directory'), exists('config', 'directory'), exists('logs', 'directory'), ...out('bin\nconfig\nlogs')] }),
    l({ title: 'Scaffold a small project', focus: 'Directory and file creation can be composed into an idempotent project scaffold.', example: 'New-Item project -ItemType Directory; New-Item project\README.md -ItemType File', task: 'Create app\config and app\logs, then create app\config\app.ini containing mode=practice and print it.', solution: "New-Item app\config,app\logs -ItemType Directory -Force | Out-Null; New-Item app\config\app.ini -ItemType File -Value 'mode=practice' -Force | Out-Null; Get-Content app\config\app.ini", checks: [exists('app/logs', 'directory'), content('app/config/app.ini', 'mode=practice'), ...out('mode=practice')] }),
  ],
  'Copy-Item': [
    l({ title: 'Overwrite a reviewed destination', focus: '-Force replaces a read-only destination after the path has been deliberately selected.', example: 'Copy-Item source.conf target.conf -Force', task: 'Copy current.conf over the existing backup.conf with -Force, then print backup.conf.', solution: 'Copy-Item current.conf backup.conf -Force; Get-Content backup.conf', files: { 'current.conf': 'version=2', 'backup.conf': 'version=1' }, setup: ["(Get-Item backup.conf).Attributes += 'ReadOnly'"], checks: [content('backup.conf', 'version=2'), ...out('version=2')] }),
    l({ title: 'Copy a directory recursively', focus: '-Recurse copies a complete hierarchy rather than only its top-level item.', example: 'Copy-Item project snapshot -Recurse', task: 'Copy project recursively to snapshot and print snapshot\config\app.ini.', solution: 'Copy-Item project snapshot -Recurse; Get-Content snapshot\config\app.ini', files: { 'project/README.md': 'project', 'project/config/app.ini': 'mode=prod' }, checks: [content('snapshot/README.md', 'project'), content('snapshot/config/app.ini', 'mode=prod'), ...out('mode=prod')] }),
    l({ title: 'Copy a selected file set', focus: '-Filter limits provider-side copying to matching names.', example: "Copy-Item logs\* archive -Filter '*.log'", task: 'Copy only .json files from incoming into reviewed, then print copied names sorted.', solution: "Copy-Item incoming\* reviewed -Filter '*.json'; Get-ChildItem reviewed -File -Name | Sort-Object", directories: ['reviewed'], files: { 'incoming/app.json': '{}', 'incoming/routes.json': '{}', 'incoming/notes.txt': 'skip' }, checks: [exists('reviewed/app.json'), exists('reviewed/routes.json'), missing('reviewed/notes.txt'), ...out('app.json\nroutes.json')] }),
    l({ title: 'Create a verified backup', focus: 'A practical copy workflow verifies content hashes instead of assuming the transfer succeeded.', example: 'Copy-Item artifact backup; Compare-Object (Get-FileHash artifact).Hash (Get-FileHash backup).Hash', task: 'Copy release.bin to backups\release.bin and print verified when their SHA-256 hashes match.', solution: 'Copy-Item release.bin backups\release.bin; if ((Get-FileHash release.bin).Hash -eq (Get-FileHash backups\release.bin).Hash) { "verified" }', directories: ['backups'], files: { 'release.bin': 'release payload' }, checks: [content('backups/release.bin', 'release payload'), ...out('verified')] }),
  ],
  'Move-Item': [
    l({ title: 'Move several files into a directory', focus: 'Move-Item accepts an array of reviewed source paths.', example: "Move-Item one.log,two.log archive", task: 'Move api.log and web.log into archive, then print the destination names sorted.', solution: 'Move-Item api.log,web.log archive; Get-ChildItem archive -File -Name | Sort-Object', directories: ['archive'], files: { 'api.log': '', 'web.log': '' }, checks: [missing('api.log'), missing('web.log'), exists('archive/api.log'), exists('archive/web.log'), ...out('api.log\nweb.log')] }),
    l({ title: 'Overwrite a stale destination', focus: '-Force completes an intentional replacement when a destination file already exists.', example: 'Move-Item current.txt archive\current.txt -Force', task: 'Move new.conf over archive\app.conf with -Force and print the result.', solution: 'Move-Item new.conf archive\app.conf -Force; Get-Content archive\app.conf', files: { 'new.conf': 'version=new', 'archive/app.conf': 'version=old' }, checks: [missing('new.conf'), content('archive/app.conf', 'version=new'), ...out('version=new')] }),
    l({ title: 'Move files selected by a pipeline', focus: 'Pipeline filtering lets metadata determine which paths are moved.', example: "Get-ChildItem -File | Where-Object Length -eq 0 | Move-Item -Destination empty", task: 'Move only zero-byte files from queue into empty, then print their names sorted.', solution: 'Get-ChildItem queue -File | Where-Object Length -eq 0 | Move-Item -Destination empty; Get-ChildItem empty -File -Name | Sort-Object', directories: ['empty'], files: { 'queue/a.txt': '', 'queue/b.txt': 'keep', 'queue/c.txt': '' }, checks: [exists('empty/a.txt'), exists('empty/c.txt'), exists('queue/b.txt'), ...out('a.txt\nc.txt')] }),
    l({ title: 'Promote a staged release', focus: 'A move workflow can archive the old target and promote the reviewed staging tree atomically within one volume.', example: 'Move-Item current archive\old; Move-Item staging current', task: 'Move current to archive\previous, promote staging to current, and print current\version.txt.', solution: 'Move-Item current archive\previous; Move-Item staging current; Get-Content current\version.txt', directories: ['archive'], files: { 'current/version.txt': 'v1', 'staging/version.txt': 'v2' }, checks: [content('archive/previous/version.txt', 'v1'), content('current/version.txt', 'v2'), missing('staging'), ...out('v2')] }),
  ],
  'Rename-Item': [
    l({ title: 'Rename with an explicit new name', focus: '-NewName makes the destination leaf clear while keeping the item in its current directory.', example: 'Rename-Item draft.txt -NewName final.txt', task: 'Rename notes.old to notes.txt using -NewName.', solution: 'Rename-Item notes.old -NewName notes.txt', files: { 'notes.old': 'notes' }, checks: [missing('notes.old'), content('notes.txt', 'notes')] }),
    l({ title: 'Preview a rename', focus: '-WhatIf shows the proposed rename without changing the file.', example: 'Rename-Item app.log app.old -WhatIf', task: 'Preview renaming report.txt to report.bak without changing either path.', solution: 'Rename-Item report.txt report.bak -WhatIf', files: { 'report.txt': 'report' }, checks: [exists('report.txt'), missing('report.bak'), contains('report.bak')] }),
    l({ title: 'Rename a batch with a script block', focus: 'A -NewName script block derives each destination from the current item.', example: "Get-ChildItem *.txt | Rename-Item -NewName { $_.BaseName + '.bak' }", task: 'Rename every .log file in logs to the same base name with a .old extension, then print names sorted.', solution: "Get-ChildItem logs -File -Filter '*.log' | Rename-Item -NewName { $_.BaseName + '.old' }; Get-ChildItem logs -File -Name | Sort-Object", files: { 'logs/api.log': '', 'logs/web.log': '', 'logs/keep.txt': '' }, checks: [exists('logs/api.old'), exists('logs/web.old'), exists('logs/keep.txt'), ...out('api.old\nkeep.txt\nweb.old')] }),
    l({ title: 'Normalize numbered artifact names', focus: 'Pattern matching and formatted numbers can turn inconsistent names into a sortable convention.', example: "Get-ChildItem 'part-*.txt' | Rename-Item -NewName { ... }", task: 'Rename part-1.txt, part-2.txt, and part-10.txt to part-01.txt, part-02.txt, and part-10.txt, then print names sorted.', solution: "Get-ChildItem 'part-*.txt' | Rename-Item -NewName { if ($_.BaseName -match 'part-(\\d+)') { 'part-{0:D2}.txt' -f [int]$Matches[1] } }; Get-ChildItem 'part-*.txt' -Name | Sort-Object", files: { 'part-1.txt': '', 'part-2.txt': '', 'part-10.txt': '' }, checks: out('part-01.txt\npart-02.txt\npart-10.txt') }),
  ],
  'Remove-Item': [
    l({ title: 'Preview deletion safely', focus: '-WhatIf reports the selected deletion without removing the item.', example: 'Remove-Item old.log -WhatIf', task: 'Preview deleting archive.log and keep the file intact.', solution: 'Remove-Item archive.log -WhatIf', files: { 'archive.log': 'keep for now' }, checks: [exists('archive.log'), contains('archive.log')] }),
    l({ title: 'Remove a directory recursively', focus: '-Recurse deletes reviewed descendants while -Force handles hidden or read-only children.', example: 'Remove-Item cache -Recurse -Force', task: 'Remove the disposable cache tree recursively while preserving data.', solution: 'Remove-Item cache -Recurse -Force', files: { 'cache/a.tmp': '', 'cache/nested/b.tmp': '', 'data/keep.txt': 'keep' }, checks: [missing('cache'), exists('data/keep.txt')] }),
    l({ title: 'Delete files selected by age metadata', focus: 'Filtering item metadata before Remove-Item keeps selection logic visible and testable.', example: 'Get-ChildItem logs | Where-Object LastWriteTime -lt $cutoff | Remove-Item', task: 'Remove only logs older than 2025-01-01 and print the remaining names.', solution: "$cutoff=[datetime]'2025-01-01'; Get-ChildItem logs -File | Where-Object LastWriteTime -lt $cutoff | Remove-Item; Get-ChildItem logs -File -Name | Sort-Object", files: { 'logs/old.log': '', 'logs/current.log': '' }, setup: ["(Get-Item logs\\old.log).LastWriteTime=[datetime]'2024-01-01'; (Get-Item logs\\current.log).LastWriteTime=[datetime]'2026-01-01'"], checks: [missing('logs/old.log'), exists('logs/current.log'), ...out('current.log')] }),
    l({ title: 'Clean reviewed temporary patterns', focus: 'A cleanup workflow previews its exact selection before deleting and reports what remains.', example: "Get-ChildItem build -Recurse -File -Include '*.tmp'", task: 'Remove every .tmp file below build, preserve all .txt files, and print the remaining relative file paths sorted.', solution: "Get-ChildItem build -Recurse -File -Filter '*.tmp' | Remove-Item; Get-ChildItem build -Recurse -File | ForEach-Object { $_.FullName.Substring((Get-Location).Path.Length+1).Replace('\\','/') } | Sort-Object", files: { 'build/a.tmp': '', 'build/keep.txt': '', 'build/nested/b.tmp': '', 'build/nested/readme.txt': '' }, checks: [missing('build/a.tmp'), missing('build/nested/b.tmp'), ...out('build/keep.txt\nbuild/nested/readme.txt')] }),
  ],
  'Get-Content': [
    l({ title: 'Read the first lines', focus: '-TotalCount reads only the beginning of a file.', example: 'Get-Content app.log -TotalCount 2', task: 'Print only the first two lines of events.log.', solution: 'Get-Content events.log -TotalCount 2', files: { 'events.log': 'start\nready\ncomplete\n' }, checks: out('start\nready') }),
    l({ title: 'Read the last lines', focus: '-Tail selects the newest records from the end of a text file.', example: 'Get-Content app.log -Tail 10', task: 'Print only the last three lines of audit.log.', solution: 'Get-Content audit.log -Tail 3', files: { 'audit.log': 'one\ntwo\nthree\nfour\nfive\n' }, checks: out('three\nfour\nfive') }),
    l({ title: 'Read a file as one string', focus: '-Raw preserves the file as one scalar string, useful for JSON and whole-document operations.', example: '(Get-Content config.json -Raw).Length', task: 'Read message.txt with -Raw, replace the newline between hello and world with one space, and print hello world.', solution: "(Get-Content message.txt -Raw).Trim() -replace '\\r?\\n',' '", files: { 'message.txt': 'hello\nworld\n' }, checks: out('hello world') }),
    l({ title: 'Parse a key-value configuration', focus: 'Reading lines and splitting once on = turns a simple configuration file into useful labeled output.', example: "Get-Content app.env | ForEach-Object { $_ -split '=',2 }", task: 'Read app.env, ignore comment lines, sort settings by key, and print mode=prod then port=8080.', solution: "Get-Content app.env | Where-Object { $_ -and -not $_.StartsWith('#') } | Sort-Object | ForEach-Object { $_ }", files: { 'app.env': '# application\nport=8080\nmode=prod\n' }, checks: out('mode=prod\nport=8080') }),
  ],
  'Set-Content': [
    l({ title: 'Write several lines', focus: '-Value accepts an array and writes one output line for each element.', example: "Set-Content list.txt -Value 'one','two'", task: 'Replace steps.txt with the three lines prepare, verify, deploy, then print them.', solution: "Set-Content steps.txt -Value 'prepare','verify','deploy'; Get-Content steps.txt", files: { 'steps.txt': 'old' }, checks: [content('steps.txt', 'prepare\nverify\ndeploy'), ...out('prepare\nverify\ndeploy')] }),
    l({ title: 'Write without a trailing newline', focus: '-NoNewline is useful for exact tokens and fixtures where an extra line ending matters.', example: "Set-Content token.txt -Value 'abc' -NoNewline", task: 'Write exactly ACTIVE to state.txt with no trailing newline and print its character count.', solution: "Set-Content state.txt -Value 'ACTIVE' -NoNewline; (Get-Content state.txt -Raw).Length", checks: [content('state.txt', 'ACTIVE'), ...out('6')] }),
    l({ title: 'Write pipeline results', focus: 'Pipeline values can flow directly into Set-Content to create a derived file.', example: '1..3 | Set-Content numbers.txt', task: 'Write the squares of 1 through 5 to squares.txt, one per line, then print the file.', solution: '1..5 | ForEach-Object { $_ * $_ } | Set-Content squares.txt; Get-Content squares.txt', checks: [content('squares.txt', '1\n4\n9\n16\n25'), ...out('1\n4\n9\n16\n25')] }),
    l({ title: 'Generate a deterministic configuration', focus: 'Calculated values can be formatted and written in a stable order for repeatable configuration generation.', example: "@('mode=prod','port=8080') | Set-Content app.conf", task: 'Create app.conf containing environment=practice, workers=4, and logging=enabled in that order, then print it.', solution: "@('environment=practice','workers=4','logging=enabled') | Set-Content app.conf; Get-Content app.conf", checks: [content('app.conf', 'environment=practice\nworkers=4\nlogging=enabled'), ...out('environment=practice\nworkers=4\nlogging=enabled')] }),
  ],
  'Add-Content': [
    l({ title: 'Append several lines', focus: '-Value accepts an array so a related group can be appended in order.', example: "Add-Content log.txt -Value 'two','three'", task: 'Append verify and deploy to steps.txt after prepare, then print all lines.', solution: "Add-Content steps.txt -Value 'verify','deploy'; Get-Content steps.txt", files: { 'steps.txt': 'prepare\n' }, checks: [content('steps.txt', 'prepare\nverify\ndeploy'), ...out('prepare\nverify\ndeploy')] }),
    l({ title: 'Append pipeline output', focus: 'Pipeline results can be appended directly without first collecting an array.', example: '1..3 | Add-Content values.txt', task: 'Append numbers 2 through 4 to numbers.txt after its existing 1, then print the file.', solution: '2..4 | Add-Content numbers.txt; Get-Content numbers.txt', files: { 'numbers.txt': '1\n' }, checks: out('1\n2\n3\n4') }),
    l({ title: 'Append to matching files', focus: 'A selected file set can be updated one item at a time while unrelated extensions remain unchanged.', example: "Get-ChildItem '*.log' | ForEach-Object { Add-Content $_ 'closed' }", task: 'Append rotated to every .log file in logs, preserve notes.txt, then print api.log and web.log.', solution: "Get-ChildItem logs -Filter '*.log' | ForEach-Object { Add-Content $_.FullName 'rotated' }; Get-Content logs\api.log,logs\web.log", files: { 'logs/api.log': 'api\n', 'logs/web.log': 'web\n', 'logs/notes.txt': 'keep\n' }, checks: [content('logs/api.log', 'api\nrotated'), content('logs/web.log', 'web\nrotated'), content('logs/notes.txt', 'keep\n'), ...out('api\nrotated\nweb\nrotated')] }),
    l({ title: 'Maintain an append-only audit trail', focus: 'Formatting a stable record before Add-Content creates a simple, reviewable audit log.', example: 'Add-Content audit.log "action=deploy status=ok"', task: 'Append action=verify status=ok and action=deploy status=ok to audit.log, then print only the appended action names.', solution: "Add-Content audit.log 'action=verify status=ok','action=deploy status=ok'; Get-Content audit.log | Select-Object -Last 2 | ForEach-Object { ($_ -split ' ')[0] -replace 'action=','' }", files: { 'audit.log': 'action=prepare status=ok\n' }, checks: out('verify\ndeploy') }),
  ],
  'Clear-Content': [
    l({ title: 'Clear several files', focus: '-Path accepts multiple files while leaving each path in place.', example: 'Clear-Content one.log,two.log', task: 'Clear api.log and web.log while keeping both files.', solution: 'Clear-Content api.log,web.log', files: { 'api.log': 'api', 'web.log': 'web' }, checks: [content('api.log', ''), content('web.log', ''), exists('api.log'), exists('web.log')] }),
    l({ title: 'Clear wildcard matches', focus: 'A wildcard path clears a reviewed filename class in one operation.', example: "Clear-Content logs\*.log", task: 'Clear every .tmp file in cache while preserving keep.txt.', solution: 'Clear-Content cache\*.tmp', files: { 'cache/a.tmp': 'a', 'cache/b.tmp': 'b', 'cache/keep.txt': 'keep' }, checks: [content('cache/a.tmp', ''), content('cache/b.tmp', ''), content('cache/keep.txt', 'keep')] }),
    l({ title: 'Clear selected files from a pipeline', focus: 'Pipeline filtering can choose files by metadata before Clear-Content mutates them.', example: 'Get-ChildItem logs | Where-Object Length -gt 1KB | Clear-Content', task: 'Clear only files larger than 5 bytes in queue, then print name:length records sorted.', solution: 'Get-ChildItem queue -File | Where-Object Length -gt 5 | Clear-Content; Get-ChildItem queue -File | Sort-Object Name | ForEach-Object { "$($_.Name):$($_.Length)" }', files: { 'queue/large.txt': '123456789', 'queue/small.txt': '123' }, checks: out('large.txt:0\nsmall.txt:3') }),
    l({ title: 'Reset generated outputs but keep structure', focus: 'A targeted recursive selection can empty generated files while preserving directories and source inputs.', example: "Get-ChildItem output -Recurse -File | Clear-Content", task: 'Clear all .log files below output, preserve output\config\keep.ini, and print the cleared relative paths sorted.', solution: "Get-ChildItem output -Recurse -File -Filter '*.log' | Clear-Content; Get-ChildItem output -Recurse -File -Filter '*.log' | ForEach-Object { $_.FullName.Substring((Get-Location).Path.Length+1).Replace('\\','/') } | Sort-Object", files: { 'output/api.log': 'api', 'output/nested/web.log': 'web', 'output/config/keep.ini': 'mode=keep' }, checks: [content('output/api.log', ''), content('output/nested/web.log', ''), content('output/config/keep.ini', 'mode=keep'), ...out('output/api.log\noutput/nested/web.log')] }),
  ],
  'Get-FileHash': [
    l({ title: 'Use another hash algorithm', focus: '-Algorithm selects a digest appropriate to the compatibility or validation requirement.', example: 'Get-FileHash artifact.bin -Algorithm SHA512', task: 'Print the MD5 hash of empty.txt in lowercase.', solution: '(Get-FileHash empty.txt -Algorithm MD5).Hash.ToLowerInvariant()', files: { 'empty.txt': '' }, checks: out('d41d8cd98f00b204e9800998ecf8427e') }),
    l({ title: 'Hash several files', focus: 'Get-FileHash accepts pipeline file objects and emits one record per path.', example: "Get-ChildItem '*.bin' | Get-FileHash", task: 'Print filename=SHA256 records for a.txt and b.txt sorted by filename.', solution: "Get-Item a.txt,b.txt | Get-FileHash -Algorithm SHA256 | Sort-Object Path | ForEach-Object { \"$([IO.Path]::GetFileName($_.Path))=$($_.Hash)\" }", files: { 'a.txt': 'alpha', 'b.txt': 'beta' }, checks: [contains('a.txt='), contains('b.txt=')] }),
    l({ title: 'Compare two file hashes', focus: 'Equal cryptographic hashes provide a strong content-equality check after a copy.', example: '(Get-FileHash a).Hash -eq (Get-FileHash b).Hash', task: 'Compare original.bin and copy.bin with SHA-256 and print match=True.', solution: '"match=$((Get-FileHash original.bin).Hash -eq (Get-FileHash copy.bin).Hash)"', files: { 'original.bin': 'same payload', 'copy.bin': 'same payload' }, checks: out('match=True') }),
    l({ title: 'Verify a checksum manifest', focus: 'A practical integrity workflow recomputes each recorded digest and reports mismatches explicitly.', example: 'Import-Csv checksums.csv | ForEach-Object { ... }', task: 'Read manifest.csv and print app.bin=OK and config.ini=OK after verifying each SHA-256 hash.', solution: "Import-Csv manifest.csv | ForEach-Object { $actual=(Get-FileHash $_.Path -Algorithm SHA256).Hash; \"$($_.Path)=$(if($actual -eq $_.Hash){'OK'}else{'FAIL'})\" }", files: { 'app.bin': 'app', 'config.ini': 'config' }, setup: ["@([pscustomobject]@{Path='app.bin';Hash=(Get-FileHash app.bin).Hash},[pscustomobject]@{Path='config.ini';Hash=(Get-FileHash config.ini).Hash}) | Export-Csv manifest.csv -NoTypeInformation"], checks: out('app.bin=OK\nconfig.ini=OK') }),
  ],
};
