import { lesson as l, out, contains, notContains, content, exists } from './helpers.mjs';

export default {
  'ConvertFrom-Csv': [
    l({ title: 'Parse another delimiter', focus: '-Delimiter parses structured text that uses a separator other than a comma.', example: "'name;team`nana;blue' | ConvertFrom-Csv -Delimiter ';'", task: 'Parse records.txt as semicolon-delimited data and print each name.', solution: "Get-Content records.txt | ConvertFrom-Csv -Delimiter ';' | Select-Object -ExpandProperty name", files: { 'records.txt': 'name;team\nana;blue\nben;green\n' }, checks: out('ana\nben') }),
    l({ title: 'Supply missing headers', focus: '-Header assigns property names when incoming delimited rows have no header line.', example: "'api,8080' | ConvertFrom-Csv -Header name,port", task: 'Parse endpoints.txt with name and port headers and print name=port rows.', solution: 'Get-Content endpoints.txt | ConvertFrom-Csv -Header name,port | ForEach-Object { "$($_.name)=$($_.port)" }', files: { 'endpoints.txt': 'api,8080\nweb,80\n' }, checks: out('api=8080\nweb=80') }),
    l({ title: 'Filter converted records', focus: 'ConvertFrom-Csv creates objects that can immediately use normal pipeline filtering and sorting.', example: '$csv | ConvertFrom-Csv | Where-Object status -eq active', task: 'Parse inline.csv, select active records, sort by name, and print their names.', solution: "Get-Content inline.csv | ConvertFrom-Csv | Where-Object status -eq active | Sort-Object name | Select-Object -ExpandProperty name", files: { 'inline.csv': 'name,status\nweb,active\ndb,inactive\napi,active\n' }, checks: out('api\nweb') }),
    l({ title: 'Summarize a CSV response body', focus: 'A practical pipeline can parse CSV text, group it, and calculate a concise result without creating an intermediate file.', example: '$response | ConvertFrom-Csv | Group-Object status', task: 'Parse response.txt and print failed=1 and ready=2 status counts alphabetically.', solution: 'Get-Content response.txt | ConvertFrom-Csv | Group-Object status | Sort-Object Name | ForEach-Object { "$($_.Name)=$($_.Count)" }', files: { 'response.txt': 'id,status\n1,ready\n2,failed\n3,ready\n' }, checks: out('failed=1\nready=2') }),
  ],
  'ConvertTo-Csv': [
    l({ title: 'Use a semicolon delimiter', focus: '-Delimiter produces CSV text for systems that expect another field separator.', example: '$objects | ConvertTo-Csv -Delimiter ";" -NoTypeInformation', task: 'Convert data.csv to semicolon-delimited text without type information.', solution: "Import-Csv data.csv | ConvertTo-Csv -Delimiter ';' -NoTypeInformation", files: { 'data.csv': 'name,team\nana,blue\n' }, checks: [contains('"name";"team"'), contains('"ana";"blue"')] }),
    l({ title: 'Select columns before conversion', focus: 'Projecting fields before ConvertTo-Csv defines a clean output contract and order.', example: '$records | Select-Object name,status | ConvertTo-Csv -NoTypeInformation', task: 'Convert inventory.csv to CSV text containing only name and status columns in that order.', solution: 'Import-Csv inventory.csv | Select-Object name,status | ConvertTo-Csv -NoTypeInformation', files: { 'inventory.csv': 'id,name,status\n1,api,up\n2,db,down\n' }, checks: [contains('"name","status"'), notContains('"id"')] }),
    l({ title: 'Create calculated CSV fields', focus: 'Calculated properties can reshape and derive fields before serialization.', example: '$rows | Select name,@{n="url";e={...}} | ConvertTo-Csv', task: 'Convert services.csv to CSV text with name and url fields, where url is http://host:port.', solution: 'Import-Csv services.csv | Select-Object name,@{Name="url";Expression={"http://$($_.host):$($_.port)"}} | ConvertTo-Csv -NoTypeInformation', files: { 'services.csv': 'name,host,port\napi,api.local,8080\n' }, checks: [contains('"name","url"'), contains('"api","http://api.local:8080"')] }),
    l({ title: 'Build and verify a CSV payload', focus: 'Serialized CSV text can be parsed again to verify record count and important fields before transmission.', example: '$csv=$rows | ConvertTo-Csv; $csv | ConvertFrom-Csv', task: 'Convert active rows in hosts.csv to CSV text, parse that text again, and print count=2 names=api,web.', solution: '$csv=Import-Csv hosts.csv | Where-Object status -eq active | Sort-Object name | ConvertTo-Csv -NoTypeInformation; $roundtrip=$csv | ConvertFrom-Csv; "count=$($roundtrip.Count) names=$(($roundtrip.name)-join ",")"', files: { 'hosts.csv': 'name,status\nweb,active\ndb,inactive\napi,active\n' }, checks: out('count=2 names=api,web') }),
  ],
  'Import-Csv': [
    l({ title: 'Import a semicolon-delimited file', focus: '-Delimiter maps non-comma tabular data into normal PowerShell objects.', example: "Import-Csv data.txt -Delimiter ';'", task: 'Import services.txt using ; and print name=port rows.', solution: "Import-Csv services.txt -Delimiter ';' | ForEach-Object { \"$($_.name)=$($_.port)\" }", files: { 'services.txt': 'name;port\napi;8080\nweb;80\n' }, checks: out('api=8080\nweb=80') }),
    l({ title: 'Assign headers to headerless data', focus: '-Header supplies a schema when the first row is actual data.', example: 'Import-Csv values.csv -Header name,value', task: 'Import headerless.csv with id and status headers and print id=status rows.', solution: 'Import-Csv headerless.csv -Header id,status | ForEach-Object { "$($_.id)=$($_.status)" }', files: { 'headerless.csv': '101,ready\n102,failed\n' }, checks: out('101=ready\n102=failed') }),
    l({ title: 'Aggregate imported numeric fields', focus: 'Imported fields are strings, so explicit numeric conversion makes arithmetic intent clear.', example: 'Import-Csv usage.csv | Measure-Object -Property @{...}', task: 'Import usage.csv and print total=12 after summing its numeric hours field.', solution: '$total=Import-Csv usage.csv | ForEach-Object { [int]$_.hours } | Measure-Object -Sum | Select-Object -ExpandProperty Sum; "total=$total"', files: { 'usage.csv': 'team,hours\nblue,5\ngreen,7\n' }, checks: out('total=12') }),
    l({ title: 'Create a regional inventory report', focus: 'Import, filtering, grouping, and sorting turn a raw CSV inventory into an operational summary.', example: 'Import-Csv inventory.csv | Where status -eq up | Group-Object region', task: 'From inventory.csv count only up hosts by region and print east=2 then west=1.', solution: 'Import-Csv inventory.csv | Where-Object status -eq up | Group-Object region | Sort-Object Name | ForEach-Object { "$($_.Name)=$($_.Count)" }', files: { 'inventory.csv': 'host,region,status\na,east,up\nb,east,down\nc,east,up\nd,west,up\n' }, checks: out('east=2\nwest=1') }),
  ],
  'Export-Csv': [
    l({ title: 'Export selected columns', focus: 'Selecting properties before Export-Csv controls the exported schema and column order.', example: '$rows | Select name,status | Export-Csv report.csv -NoTypeInformation', task: 'Export only name and port from services.csv to endpoints.csv, then print its column names as name,port.', solution: "Import-Csv services.csv | Select-Object name,port | Export-Csv endpoints.csv -NoTypeInformation; ((Import-Csv endpoints.csv | Select-Object -First 1).PSObject.Properties.Name) -join ','", files: { 'services.csv': 'name,host,port\napi,localhost,8080\nweb,localhost,80\n' }, checks: [exists('endpoints.csv'), ...out('name,port')] }),
    l({ title: 'Append another record', focus: '-Append adds compatible records without rewriting existing CSV rows.', example: '$row | Export-Csv report.csv -Append -NoTypeInformation', task: 'Append the green team record from new.csv to teams.csv, then print all team values.', solution: 'Import-Csv new.csv | Export-Csv teams.csv -Append -NoTypeInformation; Import-Csv teams.csv | Select-Object -ExpandProperty team', files: { 'teams.csv': 'name,team\nana,blue\n', 'new.csv': 'name,team\nben,green\n' }, checks: [contains('blue'), contains('green')] }),
    l({ title: 'Export with another delimiter', focus: '-Delimiter creates a file compatible with semicolon-based consumers.', example: '$rows | Export-Csv report.txt -Delimiter ";" -NoTypeInformation', task: 'Export inventory.csv to inventory.scsv using ; and no type information.', solution: "Import-Csv inventory.csv | Export-Csv inventory.scsv -Delimiter ';' -NoTypeInformation", files: { 'inventory.csv': 'name,status\napi,up\n' }, checks: [exists('inventory.scsv')] }),
    l({ title: 'Generate and validate an active-host report', focus: 'A practical export workflow filters, orders, writes, and reimports the artifact to verify its contents.', example: '$active | Export-Csv active.csv; Import-Csv active.csv', task: 'Export active hosts sorted by name to active.csv with name and region columns, then print api=west and web=east after reimporting.', solution: 'Import-Csv hosts.csv | Where-Object status -eq active | Sort-Object name | Select-Object name,region | Export-Csv active.csv -NoTypeInformation; Import-Csv active.csv | ForEach-Object { "$($_.name)=$($_.region)" }', files: { 'hosts.csv': 'name,region,status\nweb,east,active\ndb,east,inactive\napi,west,active\n' }, checks: [exists('active.csv'), ...out('api=west\nweb=east')] }),
  ],
  'ConvertTo-Json': [
    l({ title: 'Serialize a collection compactly', focus: '-Compress removes presentation whitespace while retaining JSON structure.', example: '1,2,3 | ConvertTo-Json -Compress', task: 'Convert the names api and web into one compact JSON array.', solution: "Write-Output @('api','web') -NoEnumerate | ConvertTo-Json -Compress", checks: out('["api","web"]') }),
    l({ title: 'Increase nested serialization depth', focus: '-Depth preserves nested objects beyond the shallow default depth.', example: '$object | ConvertTo-Json -Depth 5', task: 'Create an object with service.name=api and service.endpoint.port=8080, then print compact JSON at sufficient depth.', solution: "$o=[pscustomobject]@{service=[pscustomobject]@{name='api';endpoint=[pscustomobject]@{port=8080}}}; $o | ConvertTo-Json -Depth 4 -Compress", checks: out('{"service":{"name":"api","endpoint":{"port":8080}}}') }),
    l({ title: 'Select fields before JSON serialization', focus: 'Property projection prevents unrelated source columns from leaking into a JSON payload.', example: 'Import-Csv users.csv | Select name,team | ConvertTo-Json', task: 'Convert inventory.csv to compact JSON containing only name and status fields.', solution: 'Import-Csv inventory.csv | Select-Object name,status | ConvertTo-Json -Compress', files: { 'inventory.csv': 'id,name,status\n1,api,up\n2,web,up\n' }, checks: [contains('"name":"api"'), contains('"status":"up"'), notContains('"id"')] }),
    l({ title: 'Build a deployment JSON document', focus: 'A nested object can combine metadata and selected records into a practical configuration document.', example: '[pscustomobject]@{environment="prod";services=$rows} | ConvertTo-Json -Depth 4', task: 'Create deployment.json with environment=practice and active service names api and web, then parse it and print practice:api,web.', solution: "$services=Import-Csv services.csv | Where-Object status -eq active | Sort-Object name | Select-Object -ExpandProperty name; [pscustomobject]@{environment='practice';services=@($services)} | ConvertTo-Json -Depth 3 | Set-Content deployment.json; $d=Get-Content deployment.json -Raw | ConvertFrom-Json; \"$($d.environment):$(($d.services)-join ',')\"", files: { 'services.csv': 'name,status\nweb,active\ndb,inactive\napi,active\n' }, checks: [exists('deployment.json'), ...out('practice:api,web')] }),
  ],
  'ConvertFrom-Json': [
    l({ title: 'Read a nested property', focus: 'Parsed JSON becomes nested PowerShell objects accessible with normal property notation.', example: "('{\"service\":{\"port\":80}}' | ConvertFrom-Json).service.port", task: 'Parse config.json and print only service.endpoint.port.', solution: '(Get-Content config.json -Raw | ConvertFrom-Json).service.endpoint.port', files: { 'config.json': '{"service":{"name":"api","endpoint":{"port":8080}}}' }, checks: out('8080') }),
    l({ title: 'Enumerate a JSON array', focus: 'JSON arrays become PowerShell collections that flow through the pipeline.', example: "('{\"names\":[\"a\",\"b\"]}' | ConvertFrom-Json).names", task: 'Parse hosts.json and print active host names sorted.', solution: '(Get-Content hosts.json -Raw | ConvertFrom-Json).hosts | Where-Object status -eq active | Sort-Object name | Select-Object -ExpandProperty name', files: { 'hosts.json': '{"hosts":[{"name":"web","status":"active"},{"name":"db","status":"inactive"},{"name":"api","status":"active"}]}' }, checks: out('api\nweb') }),
    l({ title: 'Calculate from JSON values', focus: 'Explicit numeric properties from parsed JSON can feed normal arithmetic and aggregation.', example: '$o=Get-Content usage.json -Raw | ConvertFrom-Json; ($o.values | Measure -Sum).Sum', task: 'Parse metrics.json and print average=20 from its values array.', solution: '$m=Get-Content metrics.json -Raw | ConvertFrom-Json; $avg=$m.values | Measure-Object -Average | Select-Object -ExpandProperty Average; "average=$avg"', files: { 'metrics.json': '{"values":[10,20,30]}' }, checks: out('average=20') }),
    l({ title: 'Validate a JSON service manifest', focus: 'A practical validation workflow parses once, checks required properties, and reports each service deterministically.', example: '$manifest=Get-Content manifest.json -Raw | ConvertFrom-Json', task: 'Parse manifest.json and print api=http://api.local:8080 and web=http://web.local:80 sorted by name.', solution: '$m=Get-Content manifest.json -Raw | ConvertFrom-Json; $m.services | Sort-Object name | ForEach-Object { "$($_.name)=http://$($_.host):$($_.port)" }', files: { 'manifest.json': '{"services":[{"name":"web","host":"web.local","port":80},{"name":"api","host":"api.local","port":8080}]}' }, checks: out('api=http://api.local:8080\nweb=http://web.local:80') }),
  ],
  'ConvertTo-Xml': [
    l({ title: 'Return an XML document', focus: '-As Document returns an XML object that can be queried without reparsing text.', example: '$xml=$rows | ConvertTo-Xml -As Document -NoTypeInformation', task: 'Convert people.csv to an XML document and print the count of Object nodes.', solution: '$xml=Import-Csv people.csv | ConvertTo-Xml -As Document -NoTypeInformation; $xml.Objects.Object.Count', files: { 'people.csv': 'name,team\nana,blue\nben,green\n' }, checks: out('2') }),
    l({ title: 'Name the root element', focus: '-As String output can be embedded or saved as an XML payload after selecting source fields.', example: '$rows | ConvertTo-Xml -As String -NoTypeInformation', task: 'Convert services.csv to XML text without type information and confirm it contains the api value.', solution: 'Import-Csv services.csv | ConvertTo-Xml -As String -NoTypeInformation', files: { 'services.csv': 'name,port\napi,8080\n' }, checks: [contains('<Property Name="name">api</Property>')] }),
    l({ title: 'Project fields before XML conversion', focus: 'Selecting an explicit schema keeps XML output focused and predictable.', example: '$rows | Select name,status | ConvertTo-Xml', task: 'Convert inventory.csv to XML containing name and status but not secret.', solution: 'Import-Csv inventory.csv | Select-Object name,status | ConvertTo-Xml -As String -NoTypeInformation', files: { 'inventory.csv': 'name,status,secret\napi,up,hidden\n' }, checks: [contains('Name="name"'), contains('Name="status"'), notContains('Name="secret"')] }),
    l({ title: 'Create and query an XML report', focus: 'A workflow can serialize selected records to an XML document and immediately query the produced structure.', example: '$xml=$rows | ConvertTo-Xml -As Document; $xml.SelectNodes(...)', task: 'Convert active services to an XML document and print their name property values sorted.', solution: '$xml=Import-Csv services.csv | Where-Object status -eq active | Select-Object name | ConvertTo-Xml -As Document -NoTypeInformation; $xml.SelectNodes("//Property[@Name=\'name\']") | ForEach-Object InnerText | Sort-Object', files: { 'services.csv': 'name,status\nweb,active\ndb,inactive\napi,active\n' }, checks: out('api\nweb') }),
  ],
  'Select-Xml': [
    l({ title: 'Select an attribute', focus: 'XPath /@name targets an attribute node rather than an element body.', example: "Select-Xml config.xml -XPath '//service/@name'", task: 'Print the name attributes of every service node in services.xml.', solution: "Select-Xml services.xml -XPath '//service/@name' | ForEach-Object { $_.Node.Value }", files: { 'services.xml': '<services><service name="api"/><service name="web"/></services>' }, checks: out('api\nweb') }),
    l({ title: 'Filter nodes with an XPath predicate', focus: 'XPath predicates limit selection using attributes or child values before PowerShell receives results.', example: "Select-Xml inventory.xml -XPath '//host[@status=\"up\"]'", task: 'Print names of host nodes whose status attribute is up.', solution: "Select-Xml inventory.xml -XPath '//host[@status=\"up\"]' | ForEach-Object { $_.Node.name }", files: { 'inventory.xml': '<hosts><host name="api" status="up"/><host name="db" status="down"/><host name="web" status="up"/></hosts>' }, checks: out('api\nweb') }),
    l({ title: 'Query namespaced XML', focus: '-Namespace maps a prefix used by XPath to the document namespace URI.', example: "Select-Xml doc.xml -XPath '//x:item' -Namespace @{x='urn:items'}", task: 'Use namespace prefix x for urn:gym and print both x:name values.', solution: "Select-Xml namespaced.xml -XPath '//x:name' -Namespace @{x='urn:gym'} | ForEach-Object { $_.Node.InnerText }", files: { 'namespaced.xml': '<root xmlns="urn:gym"><name>api</name><name>web</name></root>' }, checks: out('api\nweb') }),
    l({ title: 'Build an XML endpoint report', focus: 'XPath selection plus node navigation can transform a configuration document into an operational endpoint list.', example: "Select-Xml services.xml -XPath '//service[@enabled=\"true\"]'", task: 'Select enabled services from config.xml, sort by name, and print name=http://host:port.', solution: "Select-Xml config.xml -XPath '//service[@enabled=\"true\"]' | ForEach-Object { $_.Node } | Sort-Object name | ForEach-Object { \"$($_.name)=http://$($_.host):$($_.port)\" }", files: { 'config.xml': '<config><service name="web" host="web.local" port="80" enabled="true"/><service name="db" host="db.local" port="5432" enabled="false"/><service name="api" host="api.local" port="8080" enabled="true"/></config>' }, checks: out('api=http://api.local:8080\nweb=http://web.local:80') }),
  ],
  'ConvertTo-Html': [
    l({ title: 'Select table columns', focus: '-Property controls which object fields become HTML table columns.', example: '$rows | ConvertTo-Html -Fragment -Property name,status', task: 'Convert inventory.csv to an HTML fragment containing only name and status columns.', solution: 'Import-Csv inventory.csv | ConvertTo-Html -Fragment -Property name,status | Out-String', files: { 'inventory.csv': 'name,status,secret\napi,up,hidden\n' }, checks: [contains('<th>name</th>'), contains('<th>status</th>'), notContains('<th>secret</th>')] }),
    l({ title: 'Add pre-content and post-content', focus: '-PreContent and -PostContent wrap a fragment with headings or contextual notes.', example: '$rows | ConvertTo-Html -Fragment -PreContent "<h1>Report</h1>"', task: 'Create an HTML fragment with <h1>Service Report</h1> before the table and <p>End</p> after it.', solution: 'Import-Csv services.csv | ConvertTo-Html -Fragment -PreContent "<h1>Service Report</h1>" -PostContent "<p>End</p>" | Out-String', files: { 'services.csv': 'name,status\napi,up\n' }, checks: [contains('<h1>Service Report</h1>'), contains('<p>End</p>')] }),
    l({ title: 'Create a complete HTML document', focus: '-Title and -Head generate document metadata and reusable styling around the object table.', example: '$rows | ConvertTo-Html -Title Inventory -Head "<style>...</style>"', task: 'Create report.html as a complete document titled Host Inventory and confirm the title and api row are present.', solution: 'Import-Csv hosts.csv | ConvertTo-Html -Title "Host Inventory" -Property name,status | Set-Content report.html; Get-Content report.html -Raw', files: { 'hosts.csv': 'name,status\napi,up\nweb,up\n' }, checks: [exists('report.html'), contains('<title>Host Inventory</title>'), contains('<td>api</td>')] }),
    l({ title: 'Generate an active-service dashboard', focus: 'Filtering, sorting, calculated fields, and HTML conversion create a shareable static status report.', example: '$active | ConvertTo-Html -Title Status | Set-Content status.html', task: 'Generate status.html containing only active services sorted by name with name and endpoint columns; print active=2.', solution: '$active=Import-Csv services.csv | Where-Object status -eq active | Sort-Object name | Select-Object name,@{Name="endpoint";Expression={"$($_.host):$($_.port)"}}; $active | ConvertTo-Html -Title "Active Services" | Set-Content status.html; "active=$($active.Count)"', files: { 'services.csv': 'name,host,port,status\nweb,web.local,80,active\ndb,db.local,5432,inactive\napi,api.local,8080,active\n' }, checks: [exists('status.html'), ...out('active=2')] }),
  ],
  'Out-File': [
    l({ title: 'Append output to a file', focus: '-Append preserves existing content and writes new pipeline output at the end.', example: "'next' | Out-File log.txt -Append", task: 'Append beta to log.txt after alpha using Out-File, then print both lines.', solution: "'beta' | Out-File log.txt -Append; Get-Content log.txt", files: { 'log.txt': 'alpha\n' }, checks: out('alpha\nbeta') }),
    l({ title: 'Prevent accidental overwrite', focus: '-NoClobber refuses to replace an existing file, which is useful for one-time artifacts.', example: "'data' | Out-File existing.txt -NoClobber", task: 'Attempt to write new into protected.txt with -NoClobber, catch the error, and print preserved followed by protected.', solution: "try { 'new' | Out-File protected.txt -NoClobber -ErrorAction Stop } catch { 'protected' }; Get-Content protected.txt", files: { 'protected.txt': 'preserved\n' }, checks: out('protected\npreserved') }),
    l({ title: 'Control formatted output width', focus: '-Width prevents formatted table text from wrapping at a narrow host-dependent default.', example: '$objects | Format-Table | Out-File report.txt -Width 200', task: 'Format records.csv as a table and write table.txt with width 200; print the file and preserve the full long value.', solution: 'Import-Csv records.csv | Format-Table -AutoSize | Out-File table.txt -Width 200; Get-Content table.txt', files: { 'records.csv': 'name,value\napi,abcdefghijklmnopqrstuvwxyz\n' }, checks: [contains('abcdefghijklmnopqrstuvwxyz')] }),
    l({ title: 'Write a timestamped run report', focus: 'A practical report workflow sends several deterministic lines through Out-File and appends a derived summary.', example: '$lines | Out-File run.txt; $summary | Out-File run.txt -Append', task: 'Write report.txt containing run=practice and items=3 on separate lines using Out-File, then print it.', solution: "'run=practice' | Out-File report.txt; 'items=3' | Out-File report.txt -Append; Get-Content report.txt", checks: [content('report.txt', 'run=practice\nitems=3'), ...out('run=practice\nitems=3')] }),
  ],
};
