import { lesson as l, out, contains, notContains, exists } from './helpers.mjs';

export default {
  'Get-Variable': [
    l({ title: 'Find variables by pattern', focus: 'A wildcard name discovers related variables without knowing every exact identifier.', example: "Get-Variable 'PS*'", task: 'Create GymAlpha and GymBeta, then print their names alphabetically using one wildcard Get-Variable query.', solution: '$GymAlpha=1; $GymBeta=2; Get-Variable Gym* | Sort-Object Name | Select-Object -ExpandProperty Name', checks: out('GymAlpha\nGymBeta') }),
    l({ title: 'Read only stored values', focus: '-ValueOnly returns the variable values directly rather than variable metadata objects.', example: 'Get-Variable Mode -ValueOnly', task: 'Set Region to west and print region=west using Get-Variable -ValueOnly.', solution: "$Region='west'; \"region=$(Get-Variable Region -ValueOnly)\"", checks: out('region=west') }),
    l({ title: 'Inspect variable metadata', focus: 'Variable objects expose Description, Options, and visibility information in addition to Value.', example: 'Get-Variable Mode | Select-Object Name,Options', task: 'Create GymMode with description Training mode, then print GymMode:Training mode.', solution: "Set-Variable GymMode practice -Description 'Training mode'; Get-Variable GymMode | ForEach-Object { \"$($_.Name):$($_.Description)\" }", checks: out('GymMode:Training mode') }),
    l({ title: 'Build a scoped settings report', focus: 'A prefix convention plus Get-Variable creates a compact inventory of related session settings.', example: "Get-Variable 'App*' | ForEach-Object { ... }", task: 'Set GymEnvironment=practice, GymRegion=west, and GymWorkers=4, then print name=value rows alphabetically.', solution: "$GymEnvironment='practice'; $GymRegion='west'; $GymWorkers=4; Get-Variable Gym* | Sort-Object Name | ForEach-Object { \"$($_.Name)=$($_.Value)\" }", checks: out('GymEnvironment=practice\nGymRegion=west\nGymWorkers=4') }),
  ],
  'Set-Variable': [
    l({ title: 'Attach a description', focus: '-Description records the purpose of a variable alongside its value.', example: "Set-Variable Mode practice -Description 'Current mode'", task: 'Set Region to west with description Deployment region and print that description.', solution: "Set-Variable Region west -Description 'Deployment region'; (Get-Variable Region).Description", checks: out('Deployment region') }),
    l({ title: 'Set a variable in local scope', focus: '-Scope makes the intended lifetime explicit instead of relying on the caller context.', example: 'Set-Variable Count 3 -Scope Local', task: 'Set Workers to 4 in local scope and print workers=4.', solution: 'Set-Variable Workers 4 -Scope Local; "workers=$(Get-Variable Workers -ValueOnly)"', checks: out('workers=4') }),
    l({ title: 'Protect a value as read-only', focus: '-Option ReadOnly prevents accidental changes while still allowing deliberate removal with -Force in this disposable session.', example: 'Set-Variable ApiVersion v1 -Option ReadOnly', task: 'Create GymApiVersion=v2 as a read-only variable and print its option.', solution: "Set-Variable GymApiVersion v2 -Option ReadOnly; (Get-Variable GymApiVersion).Options", checks: [contains('ReadOnly')] }),
    l({ title: 'Load settings from a manifest', focus: 'Set-Variable can turn reviewed key/value rows into scoped variables for a short workflow.', example: 'Import-Csv settings.csv | ForEach-Object { Set-Variable $_.name $_.value }', task: 'Load GymMode and GymRegion from settings.csv with Set-Variable, then print mode=practice region=west.', solution: 'Import-Csv settings.csv | ForEach-Object { Set-Variable -Name $_.name -Value $_.value }; "mode=$GymMode region=$GymRegion"', files: { 'settings.csv': 'name,value\nGymMode,practice\nGymRegion,west\n' }, checks: out('mode=practice region=west') }),
  ],
  'Remove-Variable': [
    l({ title: 'Remove several variables', focus: '-Name accepts a list so a reviewed group can be removed together.', example: 'Remove-Variable TempA,TempB', task: 'Create GymOne and GymTwo, remove both in one call, and print the number of remaining Gym* variables.', solution: '$GymOne=1; $GymTwo=2; Remove-Variable GymOne,GymTwo; @(Get-Variable Gym* -ErrorAction SilentlyContinue).Count', checks: out('0') }),
    l({ title: 'Remove variables by wildcard', focus: 'A wildcard removes a consistently named temporary variable family.', example: "Remove-Variable 'Temp*'", task: 'Create GymTempA, GymTempB, and KeepMe; remove GymTemp* and print KeepMe.', solution: "$GymTempA=1; $GymTempB=2; $KeepMe='kept'; Remove-Variable GymTemp*; Get-Variable KeepMe -ValueOnly", checks: out('kept') }),
    l({ title: 'Exclude one wildcard match', focus: '-Exclude preserves named exceptions while a wildcard selects the broader cleanup set.', example: "Remove-Variable 'Build*' -Exclude BuildKeep", task: 'Create GymBuildOne, GymBuildTwo, and GymBuildKeep; remove GymBuild* except GymBuildKeep and print the remaining name.', solution: '$GymBuildOne=1; $GymBuildTwo=2; $GymBuildKeep=3; Remove-Variable GymBuild* -Exclude GymBuildKeep; Get-Variable GymBuild* | Select-Object -ExpandProperty Name', checks: out('GymBuildKeep') }),
    l({ title: 'Clean workflow variables by prefix', focus: 'A prefix-based cleanup can remove temporary workflow state and verify that no residue remains.', example: "Get-Variable 'Run_*' | Remove-Variable", task: 'Create Run_Id, Run_Status, and Permanent; remove only Run_* through the pipeline and print run-variables=0 permanent=yes.', solution: "$Run_Id=42; $Run_Status='done'; $Permanent='yes'; Get-Variable Run_* | Remove-Variable; \"run-variables=$(@(Get-Variable Run_* -ErrorAction SilentlyContinue).Count) permanent=$Permanent\"", checks: out('run-variables=0 permanent=yes') }),
  ],
  'Get-Member': [
    l({ title: 'List methods only', focus: '-MemberType Method narrows inspection to callable behavior.', example: "'text' | Get-Member -MemberType Method", task: 'Print the ToUpper method name from a string object.', solution: "'practice' | Get-Member -MemberType Method -Name ToUpper | Select-Object -ExpandProperty Name", checks: out('ToUpper') }),
    l({ title: 'Inspect static members', focus: '-Static exposes type-level members that do not require an instance.', example: 'Get-Date | Get-Member -Static', task: 'Use Get-Member -Static on [datetime] and print the Today property name.', solution: '[datetime] | Get-Member -Static -MemberType Property -Name Today | Select-Object -ExpandProperty Name', checks: out('Today') }),
    l({ title: 'Inspect an adapted object type', focus: 'Get-Member reveals the type name and available properties created by an importer.', example: 'Import-Csv data.csv | Get-Member', task: 'Import the first row of people.csv and print its PowerShell type name followed by its NoteProperty names sorted.', solution: '$o=Import-Csv people.csv | Select-Object -First 1; ($o | Get-Member).TypeName | Select-Object -First 1; $o | Get-Member -MemberType NoteProperty | Sort-Object Name | Select-Object -ExpandProperty Name', files: { 'people.csv': 'name,team\nana,blue\n' }, checks: [contains('PSCustomObject'), contains('name'), contains('team')] }),
    l({ title: 'Audit a command output schema', focus: 'Member inspection can verify that a command returns the properties a downstream workflow expects.', example: '$sample | Get-Member -MemberType Property', task: 'Create a custom object with Name, Status, and Port and print property=name records alphabetically using Get-Member.', solution: "$o=[pscustomobject]@{Name='api';Status='up';Port=8080}; $o | Get-Member -MemberType NoteProperty | Sort-Object Name | ForEach-Object { \"property=$($_.Name.ToLowerInvariant())\" }", checks: out('property=name\nproperty=port\nproperty=status') }),
  ],
  'Write-Output': [
    l({ title: 'Write one collection without enumeration', focus: '-NoEnumerate keeps an array as one pipeline object.', example: 'Write-Output (1,2,3) -NoEnumerate', task: 'Write the array 10,20,30 with -NoEnumerate and print count=3 after assigning the single output object.', solution: '$values=Write-Output (10,20,30) -NoEnumerate; "count=$($values.Count)"', checks: out('count=3') }),
    l({ title: 'Use InputObject explicitly', focus: '-InputObject makes the value being emitted clear in longer commands.', example: 'Write-Output -InputObject ready', task: 'Emit status=ready using -InputObject.', solution: "Write-Output -InputObject 'status=ready'", checks: out('status=ready') }),
    l({ title: 'Feed output into a pipeline', focus: 'Write-Output places success-stream objects into the pipeline for filtering and transformation.', example: 'Write-Output 1 2 3 | Where-Object { $_ -gt 1 }', task: 'Write 1 through 5, keep even numbers, and print their squares.', solution: 'Write-Output 1 2 3 4 5 | Where-Object { $_ % 2 -eq 0 } | ForEach-Object { $_ * $_ }', checks: out('4\n16') }),
    l({ title: 'Emit structured workflow results', focus: 'Writing objects rather than presentation text lets downstream consumers choose their own format.', example: 'Write-Output ([pscustomobject]@{...}) | ConvertTo-Json', task: 'Write a custom success object with command=deploy, status=ok, and changes=3, convert it to compact JSON, and print it.', solution: "Write-Output ([pscustomobject]@{command='deploy';status='ok';changes=3}) | ConvertTo-Json -Compress", checks: out('{"command":"deploy","status":"ok","changes":3}') }),
  ],
  'Write-Host': [
    l({ title: 'Join host values with a separator', focus: '-Separator controls how multiple displayed objects are joined.', example: "Write-Host one two -Separator ','", task: 'Display alpha|beta|gamma using Write-Host -Separator.', solution: "Write-Host alpha beta gamma -Separator '|'", checks: out('alpha|beta|gamma') }),
    l({ title: 'Display without a newline', focus: '-NoNewline keeps the next host write on the same line.', example: "Write-Host 'loading' -NoNewline; Write-Host ' done'", task: 'Use two Write-Host calls to display status=ready on one line.', solution: "Write-Host 'status=' -NoNewline; Write-Host 'ready'", checks: out('status=ready') }),
    l({ title: 'Choose host colors', focus: '-ForegroundColor and -BackgroundColor convey presentation intent without changing pipeline data.', example: "Write-Host 'OK' -ForegroundColor Green", task: 'Display PASS in green and then print color=green as success-stream data.', solution: "Write-Host 'PASS' -ForegroundColor Green; Write-Output 'color=green'", checks: [contains('PASS'), contains('color=green')] }),
    l({ title: 'Separate presentation from data', focus: 'A workflow can show a human status with Write-Host while preserving structured success output for automation.', example: 'Write-Host "Deploying..."; Write-Output $result', task: 'Display Deploying api with Write-Host, then emit compact JSON {"service":"api","status":"ready"}.', solution: "Write-Host 'Deploying api'; [pscustomobject]@{service='api';status='ready'} | ConvertTo-Json -Compress", checks: [contains('Deploying api'), contains('{"service":"api","status":"ready"}')] }),
  ],
  'Format-Table': [
    l({ title: 'Auto-size table columns', focus: '-AutoSize calculates column widths from the incoming objects.', example: 'Get-Process | Format-Table Name,Id -AutoSize', task: 'Format services.csv as an auto-sized table with name and status and render it to text.', solution: 'Import-Csv services.csv | Format-Table name,status -AutoSize | Out-String', files: { 'services.csv': 'name,status\napi,up\nweb,down\n' }, checks: [contains('name'), contains('status'), contains('api')] }),
    l({ title: 'Add a calculated table column', focus: 'Calculated properties derive display-only columns without mutating the source objects.', example: 'Get-Process | Format-Table Name,@{Label="MB";Expression={...}}', task: 'Format values.csv with name and a doubled column, then render it to text.', solution: 'Import-Csv values.csv | Format-Table name,@{Label="doubled";Expression={2*[int]$_.value}} -AutoSize | Out-String', files: { 'values.csv': 'name,value\na,3\nb,5\n' }, checks: [contains('doubled'), contains('6'), contains('10')] }),
    l({ title: 'Group table rows by a property', focus: '-GroupBy adds headings when already-sorted objects change group value.', example: 'Get-Service | Sort Status | Format-Table -GroupBy Status', task: 'Sort hosts.csv by region and name, format a table grouped by region, and render it.', solution: 'Import-Csv hosts.csv | Sort-Object region,name | Format-Table name,status -GroupBy region | Out-String', files: { 'hosts.csv': 'name,region,status\na,east,up\nb,west,down\n' }, checks: [contains('east'), contains('west'), contains('a'), contains('b')] }),
    l({ title: 'Create a compact status dashboard', focus: 'Selection, ordering, calculated display fields, and table formatting make an effective terminal dashboard.', example: '$rows | Sort status,name | Format-Table ...', task: 'Format services.csv sorted by status then name with columns name, status, and endpoint=host:port; render the complete table.', solution: 'Import-Csv services.csv | Sort-Object status,name | Format-Table name,status,@{Label="endpoint";Expression={"$($_.host):$($_.port)"}} -AutoSize | Out-String -Width 160', files: { 'services.csv': 'name,status,host,port\napi,up,api.local,8080\nweb,down,web.local,80\n' }, checks: [contains('endpoint'), contains('api.local:8080'), contains('web.local:80')] }),
  ],
  'Format-List': [
    l({ title: 'Display all properties', focus: 'A wildcard property selection shows every visible field on each input object.', example: 'Get-Item note.txt | Format-List *', task: 'Format all properties from the single row in person.csv and render them to text.', solution: 'Import-Csv person.csv | Format-List * | Out-String', files: { 'person.csv': 'name,team,level\nana,blue,3\n' }, checks: [contains('name'), contains('team'), contains('level')] }),
    l({ title: 'Add a calculated list property', focus: 'Calculated properties can add derived values to a list view.', example: 'Get-Item file | Format-List Name,@{Label="KB";Expression={...}}', task: 'Format values.csv as name and doubled list fields, then render it.', solution: 'Import-Csv values.csv | Format-List name,@{Label="doubled";Expression={2*[int]$_.value}} | Out-String', files: { 'values.csv': 'name,value\na,4\n' }, checks: [contains('name'), contains('doubled'), contains('8')] }),
    l({ title: 'Format selected system details', focus: 'A list view makes a small set of long or descriptive properties easy to scan.', example: 'Get-Item file | Format-List FullName,Length,LastWriteTime', task: 'Format note.txt with Name, Length, and Extension and render the list.', solution: 'Get-Item note.txt | Format-List Name,Length,Extension | Out-String', files: { 'note.txt': 'hello' }, checks: [contains('Name'), contains('Length'), contains('Extension'), contains('5')] }),
    l({ title: 'Render a configuration review', focus: 'A projected object followed by Format-List creates a readable review block for one configuration record.', example: '$config | Format-List Environment,Endpoint,Workers', task: 'Read config.json and render a list with Environment, Endpoint, and Workers labels.', solution: '$c=Get-Content config.json -Raw | ConvertFrom-Json; [pscustomobject]@{Environment=$c.environment;Endpoint="http://$($c.host):$($c.port)";Workers=$c.workers} | Format-List | Out-String', files: { 'config.json': '{"environment":"practice","host":"localhost","port":8080,"workers":4}' }, checks: [contains('Environment'), contains('practice'), contains('http://localhost:8080'), contains('Workers')] }),
  ],
  'Out-String': [
    l({ title: 'Render formatted output as one string', focus: 'Without -Stream, Out-String combines formatted output into one multiline scalar.', example: '$text=Get-Process | Format-Table | Out-String', task: 'Format values.csv as a table, convert it to one string, and print string=True when the result is a string.', solution: '$text=Import-Csv values.csv | Format-Table | Out-String; "string=$($text -is [string])"', files: { 'values.csv': 'name,value\na,1\n' }, checks: out('string=True') }),
    l({ title: 'Control rendering width', focus: '-Width gives formatted objects enough horizontal space to avoid truncating important values.', example: '$objects | Format-Table | Out-String -Width 200', task: 'Render records.csv as a table at width 200 and print the text containing the complete long value.', solution: 'Import-Csv records.csv | Format-Table -AutoSize | Out-String -Width 200', files: { 'records.csv': 'name,value\napi,abcdefghijklmnopqrstuvwxyz\n' }, checks: [contains('abcdefghijklmnopqrstuvwxyz')] }),
    l({ title: 'Stream formatted lines for filtering', focus: '-Stream emits individual rendered lines so normal text filtering can select from formatted output.', example: 'Get-Process | Out-String -Stream | Select-String name', task: 'Format services.csv as a table, stream the rendered lines, and print only the line containing api.', solution: "Import-Csv services.csv | Format-Table name,status | Out-String -Stream | Where-Object { $_ -match 'api' }", files: { 'services.csv': 'name,status\napi,up\nweb,down\n' }, checks: [contains('api'), contains('up'), notContains('web')] }),
    l({ title: 'Create a text report from objects', focus: 'Object formatting followed by Out-String creates a terminal-style report that can be labeled and saved.', example: '$body=$rows | Format-Table | Out-String; "REPORT`n$body"', task: 'Create report.txt beginning SERVICE REPORT and followed by an auto-sized name/status table from services.csv, then confirm api appears.', solution: '$body=Import-Csv services.csv | Sort-Object name | Format-Table name,status -AutoSize | Out-String -Width 120; "SERVICE REPORT`n$body" | Set-Content report.txt; Get-Content report.txt -Raw', files: { 'services.csv': 'name,status\nweb,down\napi,up\n' }, checks: [exists('report.txt'), contains('SERVICE REPORT'), contains('api')] }),
  ],
  'Write-Warning': [
    l({ title: 'Capture a warning variable', focus: '-WarningVariable stores emitted warnings for later inspection while still displaying them.', example: "Write-Warning 'check' -WarningVariable notice", task: 'Write warning disk space low into notice and print captured=disk space low.', solution: "Write-Warning 'disk space low' -WarningVariable notice; \"captured=$notice\"", checks: [contains('disk space low'), contains('captured=disk space low')] }),
    l({ title: 'Suppress warning display', focus: '-WarningAction SilentlyContinue hides presentation while WarningVariable can still retain the warning record.', example: "Write-Warning 'hidden' -WarningAction SilentlyContinue -WarningVariable w", task: 'Emit maintenance pending silently into warning variable w, then print stored=maintenance pending.', solution: "Write-Warning 'maintenance pending' -WarningAction SilentlyContinue -WarningVariable w; \"stored=$w\"", checks: out('stored=maintenance pending') }),
    l({ title: 'Redirect warning output', focus: 'Stream 3 can be redirected into the success stream when a unified transcript is required.', example: "Write-Warning 'review' 3>&1", task: 'Redirect the warning review configuration to success output and convert it to plain text.', solution: "Write-Warning 'review configuration' 3>&1 | ForEach-Object { $_.Message }", checks: out('review configuration') }),
    l({ title: 'Warn for unhealthy records', focus: 'A workflow can preserve healthy data on the success stream while sending actionable concerns to the warning stream.', example: '$rows | ForEach-Object { if(...) { Write-Warning ... } }', task: 'Read services.csv and write one warning service db is down for the unhealthy row, then print warnings=1.', solution: '$warnings=@(); Import-Csv services.csv | ForEach-Object { if($_.status -ne "up"){ Write-Warning "service $($_.name) is down" -WarningVariable +warnings } }; "warnings=$($warnings.Count)"', files: { 'services.csv': 'name,status\napi,up\ndb,down\nweb,up\n' }, checks: [contains('service db is down'), contains('warnings=1')] }),
  ],
};
