import { lesson as l, out, contains, notContains, exists, nonempty, ok } from './helpers.mjs';

export default {
  'Get-Process': [
    l({ title: 'Read selected process metrics', focus: 'A process object exposes identifier, memory, CPU, and start metadata.', example: 'Get-Process -Id $PID | Select-Object Id,WorkingSet64', task: 'Print id=<current PID> memory-positive=True for the current PowerShell process.', solution: '$p=Get-Process -Id $PID; "id=$($p.Id) memory-positive=$($p.WorkingSet64 -gt 0)"', checks: [contains('memory-positive=True')] }),
    l({ title: 'Find processes by name', focus: '-Name targets a process family without manually filtering every running process.', example: 'Get-Process -Name pwsh', task: 'Print True if Get-Process -Name can find the current PowerShell process name.', solution: '$name=(Get-Process -Id $PID).ProcessName; [bool](Get-Process -Name $name -ErrorAction Stop)', checks: out('True') }),
    l({ title: 'Rank processes by memory', focus: 'Sorting a process property and selecting top records creates a quick resource snapshot.', example: 'Get-Process | Sort-Object WorkingSet64 -Descending | Select-Object -First 5', task: 'Print name:megabytes for the three processes using the most working-set memory.', solution: 'Get-Process | Sort-Object WorkingSet64 -Descending | Select-Object -First 3 | ForEach-Object { "$($_.ProcessName):$([math]::Round($_.WorkingSet64/1MB,1))" }', checks: [nonempty('A top-process report was printed.')] }),
    l({ title: 'Create a current-process diagnostic record', focus: 'Combining stable process properties yields a compact diagnostic record for logs and support.', example: '$p=Get-Process -Id $PID; "name=... id=... threads=..."', task: 'Print name=<process> id=<PID> threads=<positive-count> started=<timestamp> for the current process.', solution: '$p=Get-Process -Id $PID; "name=$($p.ProcessName) id=$($p.Id) threads=$($p.Threads.Count) started=$($p.StartTime.ToString(\'s\'))"', checks: [contains('name='), contains(' id='), contains(' threads='), contains(' started=')] }),
  ],
  'Stop-Process': [
    l({ title: 'Preview a stop by process name', focus: '-Name selects processes by executable name while -WhatIf keeps the action non-destructive.', example: 'Stop-Process -Name notepad -WhatIf', task: 'Preview stopping the current PowerShell process by its process name, then print previewed=<name>.', solution: '$name=(Get-Process -Id $PID).ProcessName; Stop-Process -Name $name -WhatIf; "previewed=$name"', checks: [contains('previewed=')] }),
    l({ title: 'Preview a pipeline-selected stop', focus: 'Process objects can flow directly to Stop-Process after their selection has been reviewed.', example: 'Get-Process notepad | Stop-Process -WhatIf', task: 'Pipe the current process object to Stop-Process -WhatIf, then print piped=<PID>.', solution: 'Get-Process -Id $PID | Stop-Process -WhatIf; "piped=$PID"', checks: [contains('piped=')] }),
    l({ title: 'Stop a disposable child process', focus: 'Stopping a process by its captured Id avoids accidentally targeting unrelated processes with the same name.', example: '$child=Start-Process ... -PassThru; Stop-Process -Id $child.Id', task: 'Start a disposable PowerShell child that sleeps, stop it by Id, wait for exit, and print stopped=True.', solution: "$child=Start-Process (Get-Process -Id $PID).Path -ArgumentList '-NoProfile','-Command','Start-Sleep -Seconds 30' -PassThru; Stop-Process -Id $child.Id; $child.WaitForExit(); \"stopped=$($child.HasExited)\"", checks: out('stopped=True') }),
    l({ title: 'Clean up several tracked child processes', focus: 'A reviewed collection of captured process objects can be stopped together and verified without broad name matching.', example: '$children | Stop-Process; $children | Wait-Process', task: 'Start two disposable sleeping PowerShell children, stop both through the pipeline, wait for both, and print stopped=2.', solution: "$exe=(Get-Process -Id $PID).Path; $children=1..2 | ForEach-Object { Start-Process $exe -ArgumentList '-NoProfile','-Command','Start-Sleep -Seconds 30' -PassThru }; $children | Stop-Process; $children | Wait-Process; \"stopped=$(@($children | Where-Object HasExited).Count)\"", checks: out('stopped=2') }),
  ],
  'Start-Sleep': [
    l({ title: 'Pause in seconds', focus: '-Seconds expresses a human-readable whole-second delay.', example: 'Start-Sleep -Seconds 1', task: 'Pause the disposable gym process for one second and print resumed.', solution: 'Start-Sleep -Seconds 1; "resumed"', checks: out('resumed') }),
    l({ title: 'Use positional milliseconds', focus: '-Milliseconds provides short test and retry delays without a full second wait.', example: 'Start-Sleep -Milliseconds 50', task: 'Sleep for 20 milliseconds and print delay-ms=20.', solution: 'Start-Sleep -Milliseconds 20; "delay-ms=20"', checks: out('delay-ms=20') }),
    l({ title: 'Delay between retry attempts', focus: 'A loop can pause between bounded attempts while making each attempt visible.', example: '1..3 | ForEach-Object { ...; Start-Sleep -Milliseconds 100 }', task: 'Print attempt=1, attempt=2, and attempt=3 with a 10-millisecond Start-Sleep after the first two attempts.', solution: '1..3 | ForEach-Object { "attempt=$_"; if($_ -lt 3){Start-Sleep -Milliseconds 10} }', checks: out('attempt=1\nattempt=2\nattempt=3') }),
    l({ title: 'Implement a bounded readiness poll', focus: 'Short sleeps inside a bounded polling loop avoid a busy wait and guarantee an eventual stop condition.', example: 'while(-not $ready -and $attempt -lt 5){ Start-Sleep ... }', task: 'Poll a counter until attempt 3, sleeping 10 milliseconds between unsuccessful checks, then print ready-at=3.', solution: '$attempt=0; do { $attempt++; if($attempt -lt 3){Start-Sleep -Milliseconds 10} } until($attempt -ge 3); "ready-at=$attempt"', checks: out('ready-at=3') }),
  ],
  'Get-Service': [
    l({ title: 'Read service status', focus: 'Service objects expose a Status value without requiring a management action.', example: 'Get-Service EventLog | Select-Object Name,Status', task: 'Print EventLog=<status> for the Windows Event Log service.', solution: '$s=Get-Service EventLog; "$($s.Name)=$($s.Status)"', checks: [contains('EventLog=')] }),
    l({ title: 'Find services by display-name pattern', focus: '-DisplayName searches human-readable names with wildcards.', example: "Get-Service -DisplayName '*Event*'", task: 'Find the Windows Event Log service by display name and print its service name.', solution: "Get-Service -DisplayName 'Windows Event Log' | Select-Object -ExpandProperty Name", checks: out('EventLog') }),
    l({ title: 'Inspect dependent services', focus: '-DependentServices reveals services that declare a dependency on the selected service.', example: 'Get-Service RpcSs -DependentServices', task: 'Print a sorted list of service names that depend on RpcSs; if none, print none.', solution: '$d=@(Get-Service RpcSs -DependentServices | Sort-Object Name | Select-Object -ExpandProperty Name); if($d.Count){$d}else{"none"}', checks: [nonempty('A dependency result was printed.')] }),
    l({ title: 'Summarize services by status', focus: 'Grouping service objects gives a quick machine-wide state inventory without changing services.', example: 'Get-Service | Group-Object Status', task: 'Print status=count rows for all services, sorted by status name.', solution: 'Get-Service | Group-Object Status | Sort-Object Name | ForEach-Object { "$($_.Name)=$($_.Count)" }', checks: [contains('Running='), contains('Stopped=')] }),
  ],
  'Start-Service': [
    l({ title: 'Preview starting by display name', focus: '-DisplayName selects the intended service using its readable label while -WhatIf previews the change.', example: "Start-Service -DisplayName 'Windows Event Log' -WhatIf", task: 'Preview starting Windows Event Log by display name, then print previewed=EventLog.', solution: "Start-Service -DisplayName 'Windows Event Log' -WhatIf; 'previewed=EventLog'", checks: out('previewed=EventLog') }),
    l({ title: 'Preview from a service object', focus: 'A reviewed Get-Service result can flow directly to Start-Service.', example: 'Get-Service EventLog | Start-Service -WhatIf', task: 'Pipe the EventLog service object into Start-Service -WhatIf, then print piped=EventLog.', solution: "Get-Service EventLog | Start-Service -WhatIf; 'piped=EventLog'", checks: out('piped=EventLog') }),
    l({ title: 'Preview several selected services', focus: 'A specific name list previews a controlled batch without broad wildcards.', example: 'Start-Service EventLog,Schedule -WhatIf', task: 'Preview starting EventLog and Schedule in one Start-Service command, then print batch=EventLog,Schedule.', solution: "Start-Service EventLog,Schedule -WhatIf; 'batch=EventLog,Schedule'", checks: out('batch=EventLog,Schedule') }),
    l({ title: 'Create a safe service-start plan', focus: 'A start plan records current state and previews only services that are stopped, without mutating the machine.', example: '$targets | Where Status -eq Stopped | Start-Service -WhatIf', task: 'Inspect EventLog and Schedule, print name=status for each, then pipe only stopped targets to Start-Service -WhatIf.', solution: '$targets=Get-Service EventLog,Schedule | Sort-Object Name; $targets | ForEach-Object { "$($_.Name)=$($_.Status)" }; $targets | Where-Object Status -eq Stopped | Start-Service -WhatIf', checks: [contains('EventLog='), contains('Schedule=')] }),
  ],
  'Stop-Service': [
    l({ title: 'Preview stopping by display name', focus: '-DisplayName selects a readable service label while -WhatIf prevents the change.', example: "Stop-Service -DisplayName 'Windows Event Log' -WhatIf", task: 'Preview stopping Windows Event Log by display name, then print previewed=EventLog.', solution: "Stop-Service -DisplayName 'Windows Event Log' -WhatIf; 'previewed=EventLog'", checks: out('previewed=EventLog') }),
    l({ title: 'Preview a pipeline-selected stop', focus: 'A reviewed service object can flow directly to Stop-Service.', example: 'Get-Service EventLog | Stop-Service -WhatIf', task: 'Pipe EventLog into Stop-Service -WhatIf, then print piped=EventLog.', solution: "Get-Service EventLog | Stop-Service -WhatIf; 'piped=EventLog'", checks: out('piped=EventLog') }),
    l({ title: 'Preview dependent-service handling', focus: '-Force allows dependent services to be included, and -WhatIf reveals that impact without applying it.', example: 'Stop-Service RpcSs -Force -WhatIf', task: 'Preview stopping RpcSs with -Force, then print forced=RpcSs.', solution: "Stop-Service RpcSs -Force -WhatIf; 'forced=RpcSs'", checks: out('forced=RpcSs') }),
    l({ title: 'Create a safe service-stop plan', focus: 'Filtering a named service set by Running status yields a targeted, reviewable stop preview.', example: '$targets | Where Status -eq Running | Stop-Service -WhatIf', task: 'Inspect EventLog and Schedule, print running=<count>, then preview stopping only running targets.', solution: '$targets=Get-Service EventLog,Schedule; "running=$(@($targets | Where-Object Status -eq Running).Count)"; $targets | Where-Object Status -eq Running | Stop-Service -WhatIf', checks: [contains('running=')] }),
  ],
  'Restart-Service': [
    l({ title: 'Preview restart by display name', focus: '-DisplayName selects a service by readable label while -WhatIf previews the restart.', example: "Restart-Service -DisplayName 'Windows Event Log' -WhatIf", task: 'Preview restarting Windows Event Log by display name, then print previewed=EventLog.', solution: "Restart-Service -DisplayName 'Windows Event Log' -WhatIf; 'previewed=EventLog'", checks: out('previewed=EventLog') }),
    l({ title: 'Preview a pipeline-selected restart', focus: 'A reviewed service object can be piped directly to Restart-Service.', example: 'Get-Service EventLog | Restart-Service -WhatIf', task: 'Pipe EventLog into Restart-Service -WhatIf, then print piped=EventLog.', solution: "Get-Service EventLog | Restart-Service -WhatIf; 'piped=EventLog'", checks: out('piped=EventLog') }),
    l({ title: 'Preview a forced restart', focus: '-Force allows dependent service impact while -WhatIf keeps the plan non-destructive.', example: 'Restart-Service EventLog -Force -WhatIf', task: 'Preview a forced restart of EventLog, then print forced=EventLog.', solution: "Restart-Service EventLog -Force -WhatIf; 'forced=EventLog'", checks: out('forced=EventLog') }),
    l({ title: 'Create a safe restart plan', focus: 'A workflow records current service state and previews the exact restart target without changing Windows.', example: '$s=Get-Service name; ...; $s | Restart-Service -WhatIf', task: 'Print before=<EventLog status>, preview its restart, then print planned=EventLog.', solution: '$s=Get-Service EventLog; "before=$($s.Status)"; $s | Restart-Service -WhatIf; "planned=$($s.Name)"', checks: [contains('before='), contains('planned=EventLog')] }),
  ],
  'Get-Module': [
    l({ title: 'List loaded modules', focus: 'Without -ListAvailable, Get-Module reports modules currently imported in the session.', example: 'Get-Module | Select-Object Name,Version', task: 'Import Microsoft.PowerShell.Utility and print its loaded module name.', solution: 'Import-Module Microsoft.PowerShell.Utility; Get-Module Microsoft.PowerShell.Utility | Select-Object -ExpandProperty Name', checks: out('Microsoft.PowerShell.Utility') }),
    l({ title: 'Read an installed module version', focus: '-ListAvailable discovers installed versions even when the module is not loaded.', example: 'Get-Module Pester -ListAvailable | Sort Version -Descending', task: 'Print a non-empty version for Microsoft.PowerShell.Utility from installed modules.', solution: 'Get-Module Microsoft.PowerShell.Utility -ListAvailable | Sort-Object Version -Descending | Select-Object -First 1 -ExpandProperty Version', checks: [nonempty('An installed module version was printed.')] }),
    l({ title: 'Inspect exported commands', focus: 'A loaded module records the command names it exports.', example: '(Get-Module module).ExportedCommands.Keys', task: 'Import Microsoft.PowerShell.Utility and print Get-Date and Get-Random from its exported command keys, sorted.', solution: 'Import-Module Microsoft.PowerShell.Utility; (Get-Module Microsoft.PowerShell.Utility).ExportedCommands.Keys | Where-Object { $_ -in "Get-Date","Get-Random" } | Sort-Object', checks: out('Get-Date\nGet-Random') }),
    l({ title: 'Create a module inventory', focus: 'Grouping the newest available module versions by name creates a concise capability inventory.', example: 'Get-Module -ListAvailable | Sort Name,Version -Descending | Group Name', task: 'Print name=version for the newest available Microsoft.PowerShell.Management and Microsoft.PowerShell.Utility modules.', solution: 'Get-Module Microsoft.PowerShell.Management,Microsoft.PowerShell.Utility -ListAvailable | Sort-Object Name,@{Expression="Version";Descending=$true} | Group-Object Name | Sort-Object Name | ForEach-Object { "$($_.Name)=$($_.Group[0].Version)" }', checks: [contains('Microsoft.PowerShell.Management='), contains('Microsoft.PowerShell.Utility=')] }),
  ],
  'Import-Module': [
    l({ title: 'Import with pass-through metadata', focus: '-PassThru returns the imported module object for immediate inspection.', example: 'Import-Module module -PassThru | Select Name,Version', task: 'Import Microsoft.PowerShell.Management with -PassThru and print name=<name>.', solution: 'Import-Module Microsoft.PowerShell.Management -PassThru | ForEach-Object { "name=$($_.Name)" }', checks: out('name=Microsoft.PowerShell.Management') }),
    l({ title: 'Force a clean module reload', focus: '-Force reloads the selected module when testing updated definitions.', example: 'Import-Module module -Force -PassThru', task: 'Force-import Microsoft.PowerShell.Utility and print loaded=True.', solution: 'Import-Module Microsoft.PowerShell.Utility -Force; "loaded=$([bool](Get-Module Microsoft.PowerShell.Utility))"', checks: out('loaded=True') }),
    l({ title: 'Import commands with a prefix', focus: '-Prefix avoids naming conflicts by adding text to imported command nouns.', example: 'Import-Module module -Prefix Gym', task: 'Create GymTools.psm1 exporting Get-Status, import it with prefix Lab, and run Get-LabStatus.', solution: "Import-Module .\\GymTools.psm1 -Prefix Lab -Force; Get-LabStatus", files: { 'GymTools.psm1': "function Get-Status { 'ready' }\nExport-ModuleMember -Function Get-Status\n" }, checks: out('ready') }),
    l({ title: 'Load and inspect a local practice module', focus: 'A local module workflow imports reviewed functions, uses them, and verifies the exported surface.', example: 'Import-Module .\\Tools.psm1 -Force -PassThru', task: 'Import GymTools.psm1, print module=GymTools exports=2, then run Get-GymStatus and receive ready.', solution: '$m=Import-Module .\\GymTools.psm1 -Force -PassThru; "module=$($m.Name) exports=$($m.ExportedFunctions.Count)"; Get-GymStatus', files: { 'GymTools.psm1': "function Get-GymStatus { 'ready' }\nfunction Get-GymVersion { '1.0' }\nExport-ModuleMember -Function Get-GymStatus,Get-GymVersion\n" }, checks: out('module=GymTools exports=2\nready') }),
  ],
  'Measure-Command': [
    l({ title: 'Measure elapsed milliseconds', focus: 'TotalMilliseconds is a convenient scalar duration for short operations.', example: '(Measure-Command { Get-Item file }).TotalMilliseconds', task: 'Measure a 10-millisecond Start-Sleep and print elapsed-positive=True.', solution: '$m=Measure-Command { Start-Sleep -Milliseconds 10 }; "elapsed-positive=$($m.TotalMilliseconds -gt 0)"', checks: out('elapsed-positive=True') }),
    l({ title: 'Measure a pipeline operation', focus: 'The measured script block can contain an entire pipeline while keeping its output out of the timing result.', example: 'Measure-Command { 1..1000 | Sort-Object }', task: 'Measure sorting numbers 100 through 1 and print ticks-positive=True.', solution: '$m=Measure-Command { 100..1 | Sort-Object | Out-Null }; "ticks-positive=$($m.Ticks -gt 0)"', checks: out('ticks-positive=True') }),
    l({ title: 'Collect repeated timing samples', focus: 'Several measurements reveal variation instead of treating one timing as definitive.', example: '1..5 | ForEach-Object { (Measure-Command {...}).TotalMilliseconds }', task: 'Measure a 5-millisecond sleep three times and print samples=3 average-positive=True.', solution: '$samples=1..3 | ForEach-Object { (Measure-Command { Start-Sleep -Milliseconds 5 }).TotalMilliseconds }; "samples=$($samples.Count) average-positive=$(($samples | Measure-Object -Average).Average -gt 0)"', checks: out('samples=3 average-positive=True') }),
    l({ title: 'Benchmark and record a workflow', focus: 'A practical benchmark records operation, sample count, and average duration without depending on a specific machine speed.', example: '$samples=...; [pscustomobject]@{...} | Export-Csv benchmark.csv', task: 'Measure Get-FileHash artifact.bin three times, export one benchmark.csv row with operation, samples, and average_ms, then print operation=hash samples=3.', solution: '$times=1..3 | ForEach-Object { (Measure-Command { Get-FileHash artifact.bin | Out-Null }).TotalMilliseconds }; [pscustomobject]@{operation="hash";samples=$times.Count;average_ms=($times | Measure-Object -Average).Average} | Export-Csv benchmark.csv -NoTypeInformation; $r=Import-Csv benchmark.csv; "operation=$($r.operation) samples=$($r.samples)"', files: { 'artifact.bin': 'payload' }, checks: [exists('benchmark.csv'), ...out('operation=hash samples=3')] }),
  ],
};
