import { lesson as l, out, contains, notContains, exists, nonempty, ok } from './helpers.mjs';

export default {
  'Get-Process': [
    l({ title: 'Read selected process metrics', focus: 'A process object exposes identifier, memory, CPU, and start metadata.', example: 'Get-Process -Id $PID | Select-Object Id,WorkingSet64', task: 'Print id=<current PID> memory-positive=True for the current PowerShell process.', solution: '$p=Get-Process -Id $PID; "id=$($p.Id) memory-positive=$($p.WorkingSet64 -gt 0)"', checks: [contains('memory-positive=True')] }),
    l({ title: 'Find processes by name', focus: '-Name targets a process family without manually filtering every running process.', example: 'Get-Process -Name pwsh', task: 'Print True if Get-Process -Name can find the current PowerShell process name.', solution: '$name=(Get-Process -Id $PID).ProcessName; [bool](Get-Process -Name $name -ErrorAction Stop)', checks: out('True') }),
    l({ title: 'Rank processes by memory', focus: 'Sorting a process property and selecting top records creates a quick resource snapshot.', example: 'Get-Process | Sort-Object WorkingSet64 -Descending | Select-Object -First 5', task: 'Print name:megabytes for the three processes using the most working-set memory.', solution: 'Get-Process | Sort-Object WorkingSet64 -Descending | Select-Object -First 3 | ForEach-Object { "$($_.ProcessName):$([math]::Round($_.WorkingSet64/1MB,1))" }', checks: [nonempty('A top-process report was printed.')] }),
    l({ title: 'Create a current-process diagnostic record', focus: 'Combining stable process properties yields a compact diagnostic record for logs and support.', example: '$p=Get-Process -Id $PID; "name=... id=... threads=..."', task: 'Print name=<process> id=<PID> threads=<positive-count> started=<timestamp> for the current process.', solution: '$p=Get-Process -Id $PID; "name=$($p.ProcessName) id=$($p.Id) threads=$($p.Threads.Count) started=$($p.StartTime.ToString(\'s\'))"', checks: [contains('name='), contains(' id='), contains(' threads='), contains(' started=')] }),
  ],
  'Stop-Process': [
    l({ title: 'Preview a stop by process name', focus: '-Name selects processes by executable name while -WhatIf keeps the action non-destructive.', example: 'Stop-Process -Name notepad -WhatIf', task: 'Preview stopping the current PowerShell process by its process name, then print previewed=<name>.', solution: '$name=(Get-Process -Id $PID).ProcessName; Stop-Process -Name $name -WhatIf; "previewed=$name"', checks: [contains('previewed=')] }),
    l({ title: 'Preview a pipeline-selected stop', focus: 'Process objects can flow directly to Stop-Process after their selection has been reviewed.', example: 'Get-Process notepad | Stop-Process -WhatIf', task: 'Pipe the current process object to Stop-Process -WhatIf, then print piped=<PID>.', solution: 'Get-Process -Id $PID | Stop-Process -WhatIf; "piped=$PID"', checks: [contains('piped=')] }),
    l({ title: 'Stop a disposable child process', focus: 'Stopping a process by its captured Id avoids accidentally targeting unrelated processes with the same name.', example: '$child=Start-Process ... -PassThru; Stop-Process -Id $child.Id', task: 'Start a disposable PowerShell child that sleeps, stop it by Id, wait for exit, and print stopped=True.', solution: "$child=Start-Process (Get-Process -Id $PID).Path -ArgumentList '-NoProfile','-Command','Start-Sleep -Seconds 30' -PassThru; Stop-Process -Id $child.Id; $child.WaitForExit(); \"stopped=$($child.HasExited)\"", checks: out('stopped=True') }),
    l({ title: 'Clean up several tracked child processes', focus: 'A reviewed collection of captured process objects can be stopped together and verified without broad name matching.', example: '$children | Stop-Process; $children | Wait-Process', task: 'Start two disposable sleeping PowerShell children, stop both through the pipeline, wait for both, and print stopped=2.', solution: "$exe=(Get-Process -Id $PID).Path; $children=1..2 | ForEach-Object { Start-Process $exe -ArgumentList '-NoProfile','-Command','Start-Sleep -Seconds 30' -PassThru }; $children | Stop-Process; $children | Wait-Process; \"stopped=$(@($children | Where-Object HasExited).Count)\"", checks: out('stopped=2') }),
  ],
  'Start-Sleep': [
    l({ title: 'Pause in seconds', focus: '-Seconds expresses a human-readable whole-second delay.', example: 'Start-Sleep -Seconds 1', task: 'Pause the disposable gym process for one second and print resumed.', solution: 'Start-Sleep -Seconds 1; "resumed"', checks: out('resumed') }),
    l({ title: 'Use positional milliseconds', focus: '-Milliseconds provides short test and retry delays without a full second wait.', example: 'Start-Sleep -Milliseconds 50', task: 'Sleep for 20 milliseconds and print delay-ms=20.', solution: 'Start-Sleep -Milliseconds 20; "delay-ms=20"', checks: out('delay-ms=20') }),
    l({ title: 'Delay between retry attempts', focus: 'A loop can pause between bounded attempts while making each attempt visible.', example: '1..3 | ForEach-Object { ...; Start-Sleep -Milliseconds 100 }', task: 'Print attempt=1, attempt=2, and attempt=3 with a 10-millisecond Start-Sleep after the first two attempts.', solution: '1..3 | ForEach-Object { "attempt=$_"; if($_ -lt 3){Start-Sleep -Milliseconds 10} }', checks: out('attempt=1\nattempt=2\nattempt=3') }),
    l({ title: 'Implement a bounded readiness poll', focus: 'Short sleeps inside a bounded polling loop avoid a busy wait and guarantee an eventual stop condition.', example: 'while(-not $ready -and $attempt -lt 5){ Start-Sleep ... }', task: 'Poll a counter until attempt 3, sleeping 10 milliseconds between unsuccessful checks, then print ready-at=3.', solution: '$attempt=0; do { $attempt++; if($attempt -lt 3){Start-Sleep -Milliseconds 10} } until($attempt -ge 3); "ready-at=$attempt"', checks: out('ready-at=3') }),
  ],
  'Get-Service': [
    l({ title: 'Read service status', focus: 'Service objects expose a Status value without requiring a management action.', example: 'Get-Service EventLog | Select-Object Name,Status', task: 'Print EventLog=<status> for the Windows Event Log service.', solution: '$s=Get-Service EventLog; "$($s.Name)=$($s.Status)"', checks: [contains('EventLog=')] }),
    l({ title: 'Find services by display-name pattern', focus: '-DisplayName searches human-readable names with wildcards.', example: "Get-Service -DisplayName '*Event*'", task: 'Find the Windows Event Log service by display name and print its service name.', solution: "Get-Service -DisplayName 'Windows Event Log' | Select-Object -ExpandProperty Name", checks: out('EventLog') }),
    l({ title: 'Inspect dependent services', focus: '-DependentServices reveals services that declare a dependency on the selected service.', example: 'Get-Service RpcSs -DependentServices', task: 'Print a sorted list of service names that depend on RpcSs; if none, print none.', solution: '$d=@(Get-Service RpcSs -DependentServices | Sort-Object Name | Select-Object -ExpandProperty Name); if($d.Count){$d}else{"none"}', checks: [nonempty('A dependency result was printed.')] }),
    l({ title: 'Summarize services by status', focus: 'Grouping service objects gives a quick machine-wide state inventory without changing services.', example: 'Get-Service | Group-Object Status', task: 'Print status=count rows for all services, sorted by status name.', solution: 'Get-Service | Group-Object Status | Sort-Object Name | ForEach-Object { "$($_.Name)=$($_.Count)" }', checks: [contains('Running='), contains('Stopped=')] }),
  ],
  'Start-Job': [
    l({ title: 'Name a background job', focus: '-Name gives a job a stable session-scoped label that is easier to query than a changing numeric Id.', example: "Start-Job -Name report { 'ready' }", task: 'Start a job named inventory that returns scanned, wait for it, print inventory=Completed, and remove it.', solution: "$job=Start-Job -Name inventory { 'scanned' }; $job | Wait-Job | Out-Null; \"$($job.Name)=$($job.State)\"; Remove-Job $job", checks: out('inventory=Completed') }),
    l({ title: 'Pass arguments into a job', focus: '-ArgumentList binds values to a param block without constructing executable command text.', example: "Start-Job -ArgumentList 4 { param($n) $n * 2 }", task: 'Start a job with argument 21 that doubles its parameter, receive the result as doubled=42, and remove it.', solution: '$job=Start-Job -ArgumentList 21 { param($n) "doubled=$($n*2)" }; $job | Wait-Job | Receive-Job; Remove-Job $job', checks: out('doubled=42') }),
    l({ title: 'Launch a reviewed job collection', focus: 'Capturing each returned job object lets a workflow await and clean up only the background work it created.', example: '$jobs=1..3 | ForEach-Object { Start-Job ... }', task: 'Start three jobs named task-1 through task-3, wait for all, print completed=3, and remove them.', solution: '$jobs=1..3 | ForEach-Object { Start-Job -Name "task-$_" -ArgumentList $_ { param($n) $n } }; $jobs | Wait-Job | Out-Null; "completed=$(@($jobs | Where-Object State -eq Completed).Count)"; $jobs | Remove-Job', checks: out('completed=3') }),
    l({ title: 'Run and summarize concurrent work', focus: 'A practical job workflow reads changing fixture data, starts independent units, receives their labeled results, sorts them, and removes the tracked jobs.', example: '$values=Get-Content work.txt; $jobs=$values | ForEach-Object { Start-Job ... }', task: 'Read jobs.txt, start one job per value that prints job=<value>, receive and sort all results, then remove every job.', solution: '$jobs=Get-Content jobs.txt | ForEach-Object { Start-Job -ArgumentList $_ { param($name) "job=$name" } }; $jobs | Wait-Job | Out-Null; $jobs | Receive-Job | Sort-Object; $jobs | Remove-Job', files: { 'jobs.txt': 'alpha-{{nonce}}\nbeta-{{nonce}}\ngamma-{{nonce}}\n' }, checks: out('job=alpha-{{nonce}}\njob=beta-{{nonce}}\njob=gamma-{{nonce}}') }),
  ],
  'Get-Job': [
    l({ title: 'Select a job by name', focus: '-Name retrieves one or more tracked jobs using their stable labels.', example: 'Get-Job -Name report', task: 'Start and complete a job named lookup, use Get-Job -Name lookup to print id-positive=True, and remove it.', solution: "$job=Start-Job -Name lookup { 'ok' }; $job | Wait-Job | Out-Null; $found=Get-Job -Name lookup; \"id-positive=$($found.Id -gt 0)\"; Remove-Job $job", checks: out('id-positive=True') }),
    l({ title: 'Filter jobs by state', focus: '-State narrows the session job table to work in a known lifecycle state.', example: 'Get-Job -State Completed', task: 'Start two short jobs, wait for them, print completed=2 using Get-Job -State Completed limited to those Ids, and remove them.', solution: '$jobs=1..2 | ForEach-Object { Start-Job { 1 } }; $jobs | Wait-Job | Out-Null; $ids=$jobs.Id; "completed=$(@(Get-Job -State Completed | Where-Object Id -in $ids).Count)"; $jobs | Remove-Job', checks: out('completed=2') }),
    l({ title: 'Inspect job metadata', focus: 'Job objects expose Id, Name, State, and HasMoreData for monitoring without consuming output.', example: 'Get-Job | Select-Object Id,Name,State,HasMoreData', task: 'Complete a job named metadata that returns payload, then print metadata|Completed|True before receiving it and cleaning up.', solution: "$job=Start-Job -Name metadata { 'payload' }; $job | Wait-Job | Out-Null; $found=Get-Job -Id $job.Id; \"$($found.Name)|$($found.State)|$($found.HasMoreData)\"; $job | Receive-Job | Out-Null; Remove-Job $job", checks: out('metadata|Completed|True') }),
    l({ title: 'Build a scoped job inventory', focus: 'Filtering by captured identifiers prevents unrelated jobs in the same session from contaminating a workflow report.', example: '$jobs | ForEach-Object { Get-Job -Id $_.Id }', task: 'Create jobs red, blue, and green, wait for them, use Get-Job on their Ids to print each name in sorted order, then remove them.', solution: '$jobs="red","blue","green" | ForEach-Object { Start-Job -Name $_ { 1 } }; $jobs | Wait-Job | Out-Null; $jobs.Id | ForEach-Object { (Get-Job -Id $_).Name } | Sort-Object; $jobs | Remove-Job', checks: out('blue\ngreen\nred') }),
  ],
  'Receive-Job': [
    l({ title: 'Keep output available after receiving it', focus: '-Keep reads available job output without marking those records as consumed.', example: 'Receive-Job $job -Keep', task: 'Run a job that prints reusable, receive it twice with -Keep, print reads=2, and remove it.', solution: "$job=Start-Job { 'reusable' }; $job | Wait-Job | Out-Null; $a=Receive-Job $job -Keep; $b=Receive-Job $job -Keep; \"reads=$(@($a,$b).Count)\"; Remove-Job $job -Force", checks: out('reads=2') }),
    l({ title: 'Wait while receiving output', focus: '-Wait blocks Receive-Job until the job reaches a terminal state while streaming its available records.', example: 'Receive-Job $job -Wait', task: 'Start a job that returns waited, use Receive-Job -Wait to print waited, and remove the job.', solution: "$job=Start-Job { 'waited' }; Receive-Job $job -Wait; Remove-Job $job", checks: out('waited') }),
    l({ title: 'Receive several jobs predictably', focus: 'A collection of completed jobs can be received together, then normal pipeline tools can normalize result order.', example: '$jobs | Receive-Job | Sort-Object', task: 'Run jobs that output 3, 1, and 2, receive all of them, sort numerically, print 1 through 3, and remove the jobs.', solution: '$jobs=3,1,2 | ForEach-Object { Start-Job -ArgumentList $_ { param($n) $n } }; $jobs | Wait-Job | Out-Null; $jobs | Receive-Job | Sort-Object; $jobs | Remove-Job', checks: out('1\n2\n3') }),
    l({ title: 'Collect a background calculation report', focus: 'A complete workflow launches bounded calculations, receives structured results, formats a deterministic report, and cleans up.', example: '$jobs=...; $results=$jobs | Receive-Job; ...', task: 'Run jobs for 2, 3, and 4 that return n and square, then print 2^2=4, 3^2=9, and 4^2=16 in order and remove them.', solution: '$jobs=2,3,4 | ForEach-Object { Start-Job -ArgumentList $_ { param($n) [pscustomobject]@{n=$n;square=$n*$n} } }; $jobs | Wait-Job | Out-Null; $jobs | Receive-Job | Sort-Object n | ForEach-Object { "$($_.n)^2=$($_.square)" }; $jobs | Remove-Job', checks: out('2^2=4\n3^2=9\n4^2=16') }),
  ],
  'Get-Module': [
    l({ title: 'List loaded modules', focus: 'Without -ListAvailable, Get-Module reports modules currently imported in the session.', example: 'Get-Module | Select-Object Name,Version', task: 'Import Microsoft.PowerShell.Archive and print its loaded module name.', solution: 'Import-Module Microsoft.PowerShell.Archive; Get-Module Microsoft.PowerShell.Archive | Select-Object -ExpandProperty Name', checks: out('Microsoft.PowerShell.Archive') }),
    l({ title: 'Read an installed module version', focus: '-ListAvailable discovers installed versions even when the module is not loaded.', example: 'Get-Module Pester -ListAvailable | Sort Version -Descending', task: 'Print a non-empty version for Microsoft.PowerShell.Archive from installed modules.', solution: 'Get-Module Microsoft.PowerShell.Archive -ListAvailable | Sort-Object Version -Descending | Select-Object -First 1 -ExpandProperty Version', checks: [nonempty('An installed module version was printed.')] }),
    l({ title: 'Inspect exported commands', focus: 'A loaded module records the command names it exports.', example: '(Get-Module module).ExportedCommands.Keys', task: 'Import Microsoft.PowerShell.Archive and print Compress-Archive and Expand-Archive from its exported command keys, sorted.', solution: 'Import-Module Microsoft.PowerShell.Archive; (Get-Module Microsoft.PowerShell.Archive).ExportedCommands.Keys | Where-Object { $_ -in "Compress-Archive","Expand-Archive" } | Sort-Object', checks: out('Compress-Archive\nExpand-Archive') }),
    l({ title: 'Create a module inventory', focus: 'Grouping the newest available module versions by name creates a concise capability inventory.', example: 'Get-Module -ListAvailable | Sort Name,Version -Descending | Group Name', task: 'Print name=version for the newest available Microsoft.PowerShell.Archive module.', solution: 'Get-Module Microsoft.PowerShell.Archive -ListAvailable | Sort-Object Version -Descending | Select-Object -First 1 | ForEach-Object { "$($_.Name)=$($_.Version)" }', checks: [contains('Microsoft.PowerShell.Archive=')] }),
  ],
  'Import-Module': [
    l({ title: 'Import with pass-through metadata', focus: '-PassThru returns the imported module object for immediate inspection.', example: 'Import-Module module -PassThru | Select Name,Version', task: 'Import Microsoft.PowerShell.Archive with -PassThru and print name=<name>.', solution: 'Import-Module Microsoft.PowerShell.Archive -PassThru | ForEach-Object { "name=$($_.Name)" }', checks: out('name=Microsoft.PowerShell.Archive') }),
    l({ title: 'Force a clean module reload', focus: '-Force reloads the selected module when testing updated definitions.', example: 'Import-Module module -Force -PassThru', task: 'Force-import Microsoft.PowerShell.Archive and print loaded=True.', solution: 'Import-Module Microsoft.PowerShell.Archive -Force; "loaded=$([bool](Get-Module Microsoft.PowerShell.Archive))"', checks: out('loaded=True') }),
    l({ title: 'Import commands with a prefix', focus: '-Prefix avoids naming conflicts by adding text to imported command nouns.', example: 'Import-Module module -Prefix Gym', task: 'Create GymTools.psm1 exporting Get-Status, import it with prefix Lab, and run Get-LabStatus.', solution: "Import-Module .\\GymTools.psm1 -Prefix Lab -Force; Get-LabStatus", files: { 'GymTools.psm1': "function Get-Status { 'ready' }\nExport-ModuleMember -Function Get-Status\n" }, checks: out('ready') }),
    l({ title: 'Load and inspect a local practice module', focus: 'A local module workflow imports reviewed functions, uses them, and verifies the exported surface.', example: 'Import-Module .\\Tools.psm1 -Force -PassThru', task: 'Import GymTools.psm1, print module=GymTools exports=2, then run Get-GymStatus and receive ready.', solution: '$m=Import-Module .\\GymTools.psm1 -Force -PassThru; "module=$($m.Name) exports=$($m.ExportedFunctions.Count)"; Get-GymStatus', files: { 'GymTools.psm1': "function Get-GymStatus { 'ready' }\nfunction Get-GymVersion { '1.0' }\nExport-ModuleMember -Function Get-GymStatus,Get-GymVersion\n" }, checks: out('module=GymTools exports=2\nready') }),
  ],
  'Measure-Command': [
    l({ title: 'Measure elapsed milliseconds', focus: 'TotalMilliseconds is a convenient scalar duration for short operations.', example: '(Measure-Command { Get-Item file }).TotalMilliseconds', task: 'Measure a 10-millisecond Start-Sleep and print elapsed-positive=True.', solution: '$m=Measure-Command { Start-Sleep -Milliseconds 10 }; "elapsed-positive=$($m.TotalMilliseconds -gt 0)"', checks: out('elapsed-positive=True') }),
    l({ title: 'Measure a pipeline operation', focus: 'The measured script block can contain an entire pipeline while keeping its output out of the timing result.', example: 'Measure-Command { 1..1000 | Sort-Object }', task: 'Measure sorting numbers 100 through 1 and print ticks-positive=True.', solution: '$m=Measure-Command { 100..1 | Sort-Object | Out-Null }; "ticks-positive=$($m.Ticks -gt 0)"', checks: out('ticks-positive=True') }),
    l({ title: 'Collect repeated timing samples', focus: 'Several measurements reveal variation instead of treating one timing as definitive.', example: '1..5 | ForEach-Object { (Measure-Command {...}).TotalMilliseconds }', task: 'Measure a 5-millisecond sleep three times and print samples=3 average-positive=True.', solution: '$samples=1..3 | ForEach-Object { (Measure-Command { Start-Sleep -Milliseconds 5 }).TotalMilliseconds }; "samples=$($samples.Count) average-positive=$(($samples | Measure-Object -Average).Average -gt 0)"', checks: out('samples=3 average-positive=True') }),
    l({ title: 'Benchmark and record a workflow', focus: 'A practical benchmark records operation, sample count, and average duration without depending on a specific machine speed.', example: '$samples=...; [pscustomobject]@{...} | Export-Csv benchmark.csv', task: 'Measure Get-FileHash artifact.bin three times, export one benchmark.csv row with operation, samples, and average_ms, then print operation=hash samples=3.', solution: '$times=1..3 | ForEach-Object { (Measure-Command { Get-FileHash artifact.bin | Out-Null }).TotalMilliseconds }; [pscustomobject]@{operation="hash";samples=$times.Count;average_ms=($times | Measure-Object -Average).Average} | Export-Csv benchmark.csv -NoTypeInformation; $r=Import-Csv benchmark.csv; "operation=$($r.operation) samples=$($r.samples)"', files: { 'artifact.bin': 'payload' }, checks: [exists('benchmark.csv'), ...out('operation=hash samples=3')] }),
  ],
};
