import { lesson as l, out, contains, nonempty, exists } from './helpers.mjs';

export default {
  'Get-Date': [
    l({ title: 'Format a UTC timestamp', focus: 'ToUniversalTime plus a format string creates a timezone-explicit timestamp.', example: '(Get-Date "2026-01-01T00:00:00Z").ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")', task: 'Format 2026-08-10 14:30 UTC as 2026-08-10T14:30:00Z.', solution: "(Get-Date '2026-08-10T14:30:00Z').ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')", checks: out('2026-08-10T14:30:00Z') }),
    l({ title: 'Perform date arithmetic', focus: 'DateTime methods such as AddDays return a new timestamp without changing the original.', example: '(Get-Date "2026-01-01").AddDays(7)', task: 'Add 10 days to 2026-02-20 and print the result as yyyy-MM-dd.', solution: "(Get-Date '2026-02-20').AddDays(10).ToString('yyyy-MM-dd')", checks: out('2026-03-02') }),
    l({ title: 'Read date components', focus: 'A DateTime object exposes year, month, day, and day-of-week properties for scheduling logic.', example: '$d=Get-Date "2026-01-01"; $d.DayOfWeek', task: 'Print year=2026 month=12 day=25 weekday=Friday for 2026-12-25.', solution: "$d=Get-Date '2026-12-25'; \"year=$($d.Year) month=$($d.Month) day=$($d.Day) weekday=$($d.DayOfWeek)\"", checks: out('year=2026 month=12 day=25 weekday=Friday') }),
    l({ title: 'Generate a dated artifact manifest', focus: 'Date arithmetic and formatting can generate deterministic daily artifact names for a bounded range.', example: '0..2 | ForEach-Object { (Get-Date "2026-01-01").AddDays($_).ToString(...) }', task: 'Print backup-20260810.zip through backup-20260814.zip, one per day.', solution: "0..4 | ForEach-Object { 'backup-{0}.zip' -f (Get-Date '2026-08-10').AddDays($_).ToString('yyyyMMdd') }", checks: out('backup-20260810.zip\nbackup-20260811.zip\nbackup-20260812.zip\nbackup-20260813.zip\nbackup-20260814.zip') }),
  ],
  'New-TimeSpan': [
    l({ title: 'Create a duration from units', focus: 'Duration parameters construct a TimeSpan without start and end timestamps.', example: 'New-TimeSpan -Hours 2 -Minutes 30', task: 'Create a span of 1 day, 2 hours, and 30 minutes and print total-hours=26.5.', solution: '$s=New-TimeSpan -Days 1 -Hours 2 -Minutes 30; "total-hours=$($s.TotalHours)"', checks: out('total-hours=26.5') }),
    l({ title: 'Read individual span components', focus: 'TimeSpan component properties describe the remainder after larger units are removed.', example: '$s=New-TimeSpan ...; "$($s.Days):$($s.Hours)"', task: 'Create a 3-day, 4-hour, 5-minute span and print days=3 hours=4 minutes=5.', solution: '$s=New-TimeSpan -Days 3 -Hours 4 -Minutes 5; "days=$($s.Days) hours=$($s.Hours) minutes=$($s.Minutes)"', checks: out('days=3 hours=4 minutes=5') }),
    l({ title: 'Compare an elapsed duration to an SLA', focus: 'A span between two timestamps can be compared numerically with a target threshold.', example: '(New-TimeSpan $start $end).TotalMinutes -le 5', task: 'Measure 09:00 to 09:04:30 and print elapsed-seconds=270 sla-met=True for a five-minute SLA.', solution: '$s=New-TimeSpan -Start "2026-01-01 09:00:00" -End "2026-01-01 09:04:30"; "elapsed-seconds=$($s.TotalSeconds) sla-met=$($s.TotalMinutes -le 5)"', checks: out('elapsed-seconds=270 sla-met=True') }),
    l({ title: 'Summarize job durations', focus: 'Creating spans from structured start and end fields enables per-job duration reporting and aggregation.', example: 'Import-Csv jobs.csv | ForEach-Object { New-TimeSpan $_.start $_.end }', task: 'Print api=5 and web=8 minute durations from jobs.csv, then total=13.', solution: '$total=0; Import-Csv jobs.csv | ForEach-Object { $m=(New-TimeSpan -Start $_.start -End $_.end).TotalMinutes; $total += $m; "$($_.name)=$m" }; "total=$total"', files: { 'jobs.csv': 'name,start,end\napi,2026-01-01T10:00:00,2026-01-01T10:05:00\nweb,2026-01-01T11:00:00,2026-01-01T11:08:00\n' }, checks: out('api=5\nweb=8\ntotal=13') }),
  ],
  'Get-Random': [
    l({ title: 'Generate within a numeric range', focus: '-Minimum is inclusive and -Maximum is exclusive for integer generation.', example: 'Get-Random -Minimum 1 -Maximum 7', task: 'Generate an integer from 10 through 19 and print in-range=True.', solution: '$n=Get-Random -Minimum 10 -Maximum 20; "in-range=$($n -ge 10 -and $n -lt 20)"', checks: out('in-range=True') }),
    l({ title: 'Select several unique inputs', focus: '-Count selects multiple items from a collection without replacement.', example: 'Get-Random -InputObject (1..10) -Count 3', task: 'Choose four unique numbers from 1 through 10 and print count=4 unique=4.', solution: '$n=Get-Random -InputObject (1..10) -Count 4; "count=$($n.Count) unique=$(@($n | Sort-Object -Unique).Count)"', checks: out('count=4 unique=4') }),
    l({ title: 'Randomize a whole collection', focus: 'Selecting Count items equal to the collection size returns every input once in randomized order.', example: '$items=1..5; Get-Random -InputObject $items -Count $items.Count', task: 'Randomize alpha, beta, and gamma with Get-Random -Count, then sort the result for verification and print all three.', solution: "$items='alpha','beta','gamma'; Get-Random -InputObject $items -Count $items.Count | Sort-Object", checks: out('alpha\nbeta\ngamma') }),
    l({ title: 'Create a bounded sample manifest', focus: 'Random sampling followed by validation can select a review subset while recording its constraints.', example: '$sample=Get-Random $items -Count 3; ...', task: 'Select three distinct hosts from hosts.txt, save them to sample.txt, and print count=3 all-from-source=True.', solution: '$source=Get-Content hosts.txt; $sample=Get-Random -InputObject $source -Count 3; $sample | Set-Content sample.txt; "count=$($sample.Count) all-from-source=$(@($sample | Where-Object { $_ -notin $source }).Count -eq 0)"', files: { 'hosts.txt': 'api\ndb\nweb\nworker\ncache\n' }, checks: [exists('sample.txt'), ...out('count=3 all-from-source=True')] }),
  ],
  'Get-Culture': [
    l({ title: 'Read the date pattern', focus: 'DateTimeFormat exposes culture-specific patterns used by formatting and parsing.', example: '(Get-Culture).DateTimeFormat.ShortDatePattern', task: 'Print a non-empty short-date pattern from the current culture.', solution: '(Get-Culture).DateTimeFormat.ShortDatePattern', checks: [nonempty('A short date pattern was printed.')] }),
    l({ title: 'Read numeric separators', focus: 'NumberFormat describes culture-specific decimal and grouping separators.', example: '(Get-Culture).NumberFormat.NumberDecimalSeparator', task: 'Print decimal=<value> group=<value> from the current culture.', solution: '$n=(Get-Culture).NumberFormat; "decimal=$($n.NumberDecimalSeparator) group=$($n.NumberGroupSeparator)"', checks: [contains('decimal='), contains(' group=')] }),
    l({ title: 'Round-trip a culture-formatted number', focus: 'Using the same culture for formatting and parsing avoids assumptions about decimal and group separators.', example: '$c=Get-Culture; $text=1234.5.ToString("N1",$c)', task: 'Format 1234.5 with the current culture, parse it with that culture, and print roundtrip=True.', solution: '$c=Get-Culture; $text=(1234.5).ToString("N1",$c); $value=[double]::Parse($text,$c); "roundtrip=$($value -eq 1234.5)"', checks: out('roundtrip=True') }),
    l({ title: 'Create a culture diagnostics record', focus: 'A compact culture record makes parsing expectations explicit without assuming a particular locale.', example: '$c=Get-Culture; "name=... decimal=... date=..."', task: 'Print name=<culture> decimal=<separator> date-pattern=<pattern> rtl=<True-or-False> from Get-Culture.', solution: '$c=Get-Culture; "name=$($c.Name) decimal=$($c.NumberFormat.NumberDecimalSeparator) date-pattern=$($c.DateTimeFormat.ShortDatePattern) rtl=$($c.TextInfo.IsRightToLeft)"', checks: [contains('name='), contains(' decimal='), contains(' date-pattern='), contains(' rtl=')] }),
  ],
  'Get-Host': [
    l({ title: 'Read the host name', focus: 'The Name property identifies the PowerShell host application running the session.', example: '(Get-Host).Name', task: 'Print a non-empty PowerShell host name.', solution: '(Get-Host).Name', checks: [nonempty('A host name was printed.')] }),
    l({ title: 'Inspect host UI capabilities', focus: 'UI and RawUI objects expose interactive host dimensions and color settings when available.', example: '(Get-Host).UI.RawUI.WindowSize', task: 'Print width-positive=True for the current host window or buffer width.', solution: '$w=(Get-Host).UI.RawUI.BufferSize.Width; "width-positive=$($w -gt 0)"', checks: out('width-positive=True') }),
    l({ title: 'Read host culture settings', focus: 'CurrentCulture and CurrentUICulture show the formatting and resource cultures used by the host.', example: '$h=Get-Host; "$($h.CurrentCulture) $($h.CurrentUICulture)"', task: 'Print culture=<name> ui=<name> from Get-Host.', solution: '$h=Get-Host; "culture=$($h.CurrentCulture.Name) ui=$($h.CurrentUICulture.Name)"', checks: [contains('culture='), contains(' ui=')] }),
    l({ title: 'Create a host diagnostic record', focus: 'A compact host record combines application identity, version, culture, and interactivity context.', example: '$h=Get-Host; "name=... version=... culture=..."', task: 'Print name=<host> version=<version> culture=<culture> instance=<guid> from Get-Host.', solution: '$h=Get-Host; "name=$($h.Name) version=$($h.Version) culture=$($h.CurrentCulture.Name) instance=$($h.InstanceId)"', checks: [contains('name='), contains(' version='), contains(' culture='), contains(' instance=')] }),
  ],
  'Get-CimInstance': [
    l({ title: 'Query selected OS properties', focus: '-Property requests only the CIM fields needed by the workflow.', example: 'Get-CimInstance Win32_OperatingSystem -Property Caption,Version', task: 'Print caption=<value> version=<value> for Win32_OperatingSystem.', solution: '$o=Get-CimInstance Win32_OperatingSystem -Property Caption,Version; "caption=$($o.Caption) version=$($o.Version)"', checks: [contains('caption='), contains(' version=')] }),
    l({ title: 'Filter logical disks in CIM', focus: '-Filter applies a WQL predicate at the CIM provider instead of retrieving every instance.', example: "Get-CimInstance Win32_LogicalDisk -Filter 'DriveType=3'", task: 'Print device IDs for fixed logical disks, sorted.', solution: "Get-CimInstance Win32_LogicalDisk -Filter 'DriveType=3' | Sort-Object DeviceID | Select-Object -ExpandProperty DeviceID", checks: [nonempty('At least one fixed logical disk was printed.')] }),
    l({ title: 'Query a CIM class namespace explicitly', focus: '-Namespace makes the management namespace clear when class names might overlap.', example: 'Get-CimInstance -Namespace root/cimv2 -ClassName Win32_ComputerSystem', task: 'Query Win32_ComputerSystem in root/cimv2 and print manufacturer=<value> model=<value>.', solution: '$c=Get-CimInstance -Namespace root/cimv2 -ClassName Win32_ComputerSystem; "manufacturer=$($c.Manufacturer) model=$($c.Model)"', checks: [contains('manufacturer='), contains(' model=')] }),
    l({ title: 'Create a CIM health snapshot', focus: 'Several focused CIM queries can produce a compact host snapshot without parsing command-line text.', example: '$os=Get-CimInstance Win32_OperatingSystem; $cs=Get-CimInstance Win32_ComputerSystem', task: 'Print os=<caption> memory-gb=<positive-number> processors=<positive-count> using CIM.', solution: '$os=Get-CimInstance Win32_OperatingSystem; $cs=Get-CimInstance Win32_ComputerSystem; "os=$($os.Caption) memory-gb=$([math]::Round($cs.TotalPhysicalMemory/1GB,1)) processors=$($cs.NumberOfLogicalProcessors)"', checks: [contains('os='), contains(' memory-gb='), contains(' processors=')] }),
  ],
  'Get-ComputerInfo': [
    l({ title: 'Select one computer-info property', focus: '-Property limits the expensive inventory to requested fields.', example: 'Get-ComputerInfo -Property OsName', task: 'Print a non-empty OsArchitecture value.', solution: 'Get-ComputerInfo -Property OsArchitecture | Select-Object -ExpandProperty OsArchitecture', checks: [nonempty('The OS architecture was printed.')] }),
    l({ title: 'Select properties by wildcard', focus: 'A property wildcard discovers related inventory fields such as Windows version details.', example: "Get-ComputerInfo -Property 'Windows*Version'", task: 'Request WindowsProductName and WindowsVersion and print product=<value> version=<value>.', solution: '$c=Get-ComputerInfo -Property WindowsProductName,WindowsVersion; "product=$($c.WindowsProductName) version=$($c.WindowsVersion)"', checks: [contains('product='), contains(' version=')] }),
    l({ title: 'Read hardware summary fields', focus: 'Computer information combines operating system and computer-system inventory in one object.', example: 'Get-ComputerInfo -Property CsManufacturer,CsModel', task: 'Print manufacturer=<value> model=<value> from computer information.', solution: '$c=Get-ComputerInfo -Property CsManufacturer,CsModel; "manufacturer=$($c.CsManufacturer) model=$($c.CsModel)"', checks: [contains('manufacturer='), contains(' model=')] }),
    l({ title: 'Export a focused support snapshot', focus: 'A selected computer-info object can be serialized as a small support artifact instead of dumping every property.', example: 'Get-ComputerInfo -Property ... | ConvertTo-Json | Set-Content support.json', task: 'Write support.json with WindowsProductName, WindowsVersion, and OsArchitecture, then parse it and print fields=3.', solution: 'Get-ComputerInfo -Property WindowsProductName,WindowsVersion,OsArchitecture | Select-Object WindowsProductName,WindowsVersion,OsArchitecture | ConvertTo-Json | Set-Content support.json; $o=Get-Content support.json -Raw | ConvertFrom-Json; "fields=$(@($o.PSObject.Properties).Count)"', checks: [exists('support.json'), ...out('fields=3')] }),
  ],
  'Get-HotFix': [
    l({ title: 'Count installed hotfix records', focus: 'Wrapping output in an array gives a reliable count even when a machine reports zero or one record.', example: '@(Get-HotFix).Count', task: 'Print hotfix-count=<nonnegative-count>.', solution: '"hotfix-count=$(@(Get-HotFix).Count)"', checks: [contains('hotfix-count=')] }),
    l({ title: 'Select common hotfix fields', focus: 'HotFixID, Description, and InstalledOn form a useful update inventory projection.', example: 'Get-HotFix | Select HotFixID,Description,InstalledOn', task: 'Print id:description records for up to the first three hotfixes; print none if no records exist.', solution: '$h=@(Get-HotFix | Select-Object -First 3); if($h.Count){$h | ForEach-Object { "$($_.HotFixID):$($_.Description)" }}else{"none"}', checks: [nonempty('A hotfix inventory result was printed.')] }),
    l({ title: 'Sort update records by installation date', focus: 'Sorting InstalledOn descending surfaces the newest recorded updates first.', example: 'Get-HotFix | Sort InstalledOn -Descending | Select -First 1', task: 'Print newest=<HotFixID> for the newest dated hotfix, or newest=none when no records exist.', solution: '$h=Get-HotFix | Where-Object InstalledOn | Sort-Object InstalledOn -Descending | Select-Object -First 1; if($h){"newest=$($h.HotFixID)"}else{"newest=none"}', checks: [contains('newest=')] }),
    l({ title: 'Create a hotfix summary by description', focus: 'Grouping hotfix objects by Description produces a concise update-category summary.', example: 'Get-HotFix | Group-Object Description', task: 'Print description=count rows sorted, or no-hotfix-records if none are returned.', solution: '$h=@(Get-HotFix); if($h.Count){$h | Group-Object Description | Sort-Object Name | ForEach-Object { "$($_.Name)=$($_.Count)" }}else{"no-hotfix-records"}', checks: [nonempty('A grouped hotfix summary was printed.')] }),
  ],
  'Get-Disk': [
    l({ title: 'Read disk health status', focus: 'HealthStatus provides a quick management-layer assessment for each disk.', example: 'Get-Disk | Select Number,HealthStatus', task: 'Print disk=<number> health=<status> for the first disk.', solution: '$d=Get-Disk | Sort-Object Number | Select-Object -First 1; "disk=$($d.Number) health=$($d.HealthStatus)"', checks: [contains('disk='), contains(' health=')] }),
    l({ title: 'Report disk sizes', focus: 'Disk Size is a byte count that can be converted to readable gigabytes.', example: 'Get-Disk | ForEach-Object { $_.Size/1GB }', task: 'Print disk=<number> size-gb=<positive-value> for every disk.', solution: 'Get-Disk | Sort-Object Number | ForEach-Object { "disk=$($_.Number) size-gb=$([math]::Round($_.Size/1GB,1))" }', checks: [nonempty('A disk size report was printed.')] }),
    l({ title: 'Filter disks by operational status', focus: 'Filtering BusType or OperationalStatus focuses the inventory on disks relevant to a workflow.', example: 'Get-Disk | Where OperationalStatus -contains Online', task: 'Print online-disks=<count> for disks whose OperationalStatus contains Online.', solution: '"online-disks=$(@(Get-Disk | Where-Object OperationalStatus -contains Online).Count)"', checks: [contains('online-disks=')] }),
    l({ title: 'Create a disk inventory record', focus: 'Selected disk identity, bus, partition style, size, and health provide a practical storage snapshot.', example: 'Get-Disk | Select Number,FriendlyName,BusType,PartitionStyle,Size,HealthStatus', task: 'Print number|bus|partition|size-gb|health for each disk sorted by number.', solution: 'Get-Disk | Sort-Object Number | ForEach-Object { "$($_.Number)|$($_.BusType)|$($_.PartitionStyle)|$([math]::Round($_.Size/1GB,1))|$($_.HealthStatus)" }', checks: [nonempty('A detailed disk inventory was printed.')] }),
  ],
  'Get-Volume': [
    l({ title: 'Read volume file-system details', focus: 'Volume objects expose drive letter, filesystem type, and health.', example: 'Get-Volume C | Select DriveLetter,FileSystem,HealthStatus', task: 'Print drive=<letter> filesystem=<type> for the first drive-letter volume.', solution: '$v=Get-Volume | Where-Object DriveLetter | Sort-Object DriveLetter | Select-Object -First 1; "drive=$($v.DriveLetter) filesystem=$($v.FileSystem)"', checks: [contains('drive='), contains(' filesystem=')] }),
    l({ title: 'Report free space', focus: 'SizeRemaining and Size can be converted into readable capacity metrics.', example: 'Get-Volume | Select DriveLetter,SizeRemaining,Size', task: 'Print drive=<letter> free-gb=<nonnegative> for each drive-letter volume.', solution: 'Get-Volume | Where-Object DriveLetter | Sort-Object DriveLetter | ForEach-Object { "drive=$($_.DriveLetter) free-gb=$([math]::Round($_.SizeRemaining/1GB,1))" }', checks: [nonempty('A volume free-space report was printed.')] }),
    l({ title: 'Find volumes needing attention', focus: 'HealthStatus filtering identifies volumes whose management status is not Healthy.', example: 'Get-Volume | Where HealthStatus -ne Healthy', task: 'Print unhealthy-volumes=<count>.', solution: '"unhealthy-volumes=$(@(Get-Volume | Where-Object HealthStatus -ne Healthy).Count)"', checks: [contains('unhealthy-volumes=')] }),
    l({ title: 'Create a volume capacity summary', focus: 'A practical volume report calculates used percentage from size and remaining space without changing storage.', example: 'Get-Volume | ForEach-Object { ... percent ... }', task: 'Print drive=<letter> used-percent=<number> health=<status> for each drive-letter volume.', solution: 'Get-Volume | Where-Object { $_.DriveLetter -and $_.Size -gt 0 } | Sort-Object DriveLetter | ForEach-Object { $used=100*(1-$_.SizeRemaining/$_.Size); "drive=$($_.DriveLetter) used-percent=$([math]::Round($used,1)) health=$($_.HealthStatus)" }', checks: [nonempty('A volume capacity summary was printed.')] }),
  ],
};
