import { lesson as l, out, contains, nonempty, exists, content } from './helpers.mjs';

export default {
  'Get-NetIPAddress': [
    l({ title: 'Filter by address family', focus: '-AddressFamily limits results to IPv4 or IPv6 before pipeline processing.', example: 'Get-NetIPAddress -AddressFamily IPv6', task: 'Print ipv4-count=<positive-count> for IPv4 addresses.', solution: '"ipv4-count=$(@(Get-NetIPAddress -AddressFamily IPv4).Count)"', checks: [contains('ipv4-count=')] }),
    l({ title: 'Select addresses for one interface', focus: '-InterfaceAlias targets a named adapter instead of filtering a full address table afterward.', example: 'Get-NetIPAddress -InterfaceAlias Ethernet', task: 'Find the first IPv4 interface alias, query that alias explicitly, and print alias=<name> addresses=<count>.', solution: '$alias=Get-NetIPAddress -AddressFamily IPv4 | Select-Object -First 1 -ExpandProperty InterfaceAlias; $addresses=@(Get-NetIPAddress -AddressFamily IPv4 -InterfaceAlias $alias); "alias=$alias addresses=$($addresses.Count)"', checks: [contains('alias='), contains(' addresses=')] }),
    l({ title: 'Inspect prefix metadata', focus: 'PrefixLength and AddressState provide subnet and lifecycle context for each IP address.', example: 'Get-NetIPAddress -AddressFamily IPv4 | Select IPAddress,PrefixLength,AddressState', task: 'Print address/prefix state=<state> rows for IPv4 addresses, sorted by address.', solution: 'Get-NetIPAddress -AddressFamily IPv4 | Sort-Object IPAddress | ForEach-Object { "$($_.IPAddress)/$($_.PrefixLength) state=$($_.AddressState)" }', checks: [nonempty('An IPv4 prefix report was printed.')] }),
    l({ title: 'Create a usable-address inventory', focus: 'Filtering address state and origin fields creates a concise interface/address inventory for diagnostics.', example: 'Get-NetIPAddress IPv4 | Where AddressState -eq Preferred', task: 'Print alias=address/prefix for preferred IPv4 addresses, sorted by alias then address.', solution: 'Get-NetIPAddress -AddressFamily IPv4 | Where-Object AddressState -eq Preferred | Sort-Object InterfaceAlias,IPAddress | ForEach-Object { "$($_.InterfaceAlias)=$($_.IPAddress)/$($_.PrefixLength)" }', checks: [nonempty('A preferred-address inventory was printed.')] }),
  ],
  'Get-NetIPConfiguration': [
    l({ title: 'Inspect detailed configuration', focus: '-Detailed includes additional adapter, route, DNS, and profile information.', example: 'Get-NetIPConfiguration -Detailed', task: 'Print detailed-count=<positive-count> for network configurations.', solution: '"detailed-count=$(@(Get-NetIPConfiguration -Detailed).Count)"', checks: [contains('detailed-count=')] }),
    l({ title: 'Query one interface alias', focus: '-InterfaceAlias requests one configuration directly.', example: 'Get-NetIPConfiguration -InterfaceAlias Ethernet', task: 'Find the first interface alias, query it with -InterfaceAlias, and print its alias.', solution: '$alias=Get-NetIPConfiguration | Select-Object -First 1 -ExpandProperty InterfaceAlias; Get-NetIPConfiguration -InterfaceAlias $alias | Select-Object -ExpandProperty InterfaceAlias', checks: [nonempty('An interface alias was printed.')] }),
    l({ title: 'Read IPv4 and gateway context', focus: 'Nested IPv4Address and IPv4DefaultGateway properties describe host and route configuration together.', example: '$c=Get-NetIPConfiguration; $c.IPv4Address.IPAddress', task: 'Print alias=<name> ipv4=<value-or-none> gateway=<value-or-none> for the first configuration.', solution: '$c=Get-NetIPConfiguration | Select-Object -First 1; $ip=if($c.IPv4Address){$c.IPv4Address[0].IPAddress}else{"none"}; $gw=if($c.IPv4DefaultGateway){$c.IPv4DefaultGateway[0].NextHop}else{"none"}; "alias=$($c.InterfaceAlias) ipv4=$ip gateway=$gw"', checks: [contains('alias='), contains(' ipv4='), contains(' gateway=')] }),
    l({ title: 'Create an interface configuration summary', focus: 'Flattening nested configuration properties creates a practical one-line record per interface.', example: 'Get-NetIPConfiguration | ForEach-Object { ... }', task: 'Print alias|ipv4-count|dns-count records for every interface, sorted by alias.', solution: 'Get-NetIPConfiguration | Sort-Object InterfaceAlias | ForEach-Object { "$($_.InterfaceAlias)|$(@($_.IPv4Address).Count)|$(@($_.DNSServer.ServerAddresses).Count)" }', checks: [nonempty('An interface configuration summary was printed.')] }),
  ],
  'Get-NetAdapter': [
    l({ title: 'Read adapter status', focus: 'Status reports whether a network adapter is operationally Up or disconnected.', example: 'Get-NetAdapter | Select Name,Status', task: 'Print name=status for the first network adapter.', solution: '$a=Get-NetAdapter | Sort-Object Name | Select-Object -First 1; "$($a.Name)=$($a.Status)"', checks: [nonempty('An adapter status record was printed.')] }),
    l({ title: 'Include hidden adapters', focus: '-IncludeHidden includes adapters omitted from the default view.', example: 'Get-NetAdapter -IncludeHidden', task: 'Print visible=<count> all=<count> and verify all is not smaller than visible.', solution: '$visible=@(Get-NetAdapter).Count; $all=@(Get-NetAdapter -IncludeHidden).Count; "visible=$visible all=$all valid=$($all -ge $visible)"', checks: [contains('valid=True')] }),
    l({ title: 'Inspect link properties', focus: 'LinkSpeed, MacAddress, and InterfaceDescription provide physical and virtual adapter context.', example: 'Get-NetAdapter | Select Name,LinkSpeed,MacAddress', task: 'Print name|status|link-speed records for all adapters sorted by name.', solution: 'Get-NetAdapter | Sort-Object Name | ForEach-Object { "$($_.Name)|$($_.Status)|$($_.LinkSpeed)" }', checks: [nonempty('An adapter link report was printed.')] }),
    l({ title: 'Create an active-adapter inventory', focus: 'Filtering Up adapters and selecting stable fields yields a concise connectivity snapshot.', example: 'Get-NetAdapter | Where Status -eq Up | Select ...', task: 'Print up-adapters=<count>, then name=mac records for every Up adapter sorted by name.', solution: '$up=@(Get-NetAdapter | Where-Object Status -eq Up | Sort-Object Name); "up-adapters=$($up.Count)"; $up | ForEach-Object { "$($_.Name)=$($_.MacAddress)" }', checks: [contains('up-adapters=')] }),
  ],
  'Get-NetRoute': [
    l({ title: 'Find default IPv4 routes', focus: 'DestinationPrefix 0.0.0.0/0 identifies IPv4 default-route candidates.', example: "Get-NetRoute -DestinationPrefix '0.0.0.0/0'", task: 'Print default-routes=<count> for IPv4 default routes.', solution: '"default-routes=$(@(Get-NetRoute -AddressFamily IPv4 -DestinationPrefix \'0.0.0.0/0\' -ErrorAction SilentlyContinue).Count)"', checks: [contains('default-routes=')] }),
    l({ title: 'Inspect route metrics', focus: 'RouteMetric and InterfaceMetric help explain which candidate route Windows prefers.', example: 'Get-NetRoute IPv4 | Select DestinationPrefix,RouteMetric,InterfaceMetric', task: 'Print prefix metric=<route-metric> interface=<index> for the first IPv4 route.', solution: '$r=Get-NetRoute -AddressFamily IPv4 | Sort-Object RouteMetric | Select-Object -First 1; "$($r.DestinationPrefix) metric=$($r.RouteMetric) interface=$($r.InterfaceIndex)"', checks: [contains(' metric='), contains(' interface=')] }),
    l({ title: 'Filter routes by interface', focus: '-InterfaceIndex targets the route table associated with one selected adapter.', example: 'Get-NetRoute -InterfaceIndex 12', task: 'Find the first IPv4 route interface index, query it explicitly, and print route-count=<count>.', solution: '$index=Get-NetRoute -AddressFamily IPv4 | Select-Object -First 1 -ExpandProperty InterfaceIndex; "route-count=$(@(Get-NetRoute -AddressFamily IPv4 -InterfaceIndex $index).Count)"', checks: [contains('route-count=')] }),
    l({ title: 'Create a route decision report', focus: 'Sorting by combined route and interface metrics provides a useful view of candidate preference.', example: 'Get-NetRoute IPv4 | Sort @{e={$_.RouteMetric+$_.InterfaceMetric}}', task: 'Print the five lowest-metric IPv4 routes as prefix via next-hop metric=total.', solution: 'Get-NetRoute -AddressFamily IPv4 | Sort-Object @{Expression={$_.RouteMetric+$_.InterfaceMetric}} | Select-Object -First 5 | ForEach-Object { "$($_.DestinationPrefix) via $($_.NextHop) metric=$($_.RouteMetric+$_.InterfaceMetric)" }', checks: [nonempty('A ranked route report was printed.')] }),
  ],
  'Get-NetTCPConnection': [
    l({ title: 'Count listening endpoints', focus: '-State Listen limits results to local TCP listeners.', example: 'Get-NetTCPConnection -State Listen', task: 'Print listeners=<count>.', solution: '"listeners=$(@(Get-NetTCPConnection -State Listen).Count)"', checks: [contains('listeners=')] }),
    l({ title: 'Inspect local listening ports', focus: 'LocalAddress and LocalPort identify where each listener accepts connections.', example: 'Get-NetTCPConnection -State Listen | Select LocalAddress,LocalPort', task: 'Print unique listening local ports in numeric order.', solution: 'Get-NetTCPConnection -State Listen | Select-Object -ExpandProperty LocalPort | Sort-Object -Unique', checks: [nonempty('At least one listening port was printed.')] }),
    l({ title: 'Associate connections with processes', focus: 'OwningProcess links TCP endpoints to process records.', example: 'Get-NetTCPConnection | ForEach-Object { Get-Process -Id $_.OwningProcess }', task: 'Print port=process for up to five listening TCP endpoints with resolvable owning processes.', solution: 'Get-NetTCPConnection -State Listen | Sort-Object LocalPort | Select-Object -First 5 | ForEach-Object { $p=Get-Process -Id $_.OwningProcess -ErrorAction SilentlyContinue; if($p){"$($_.LocalPort)=$($p.ProcessName)"} }', checks: [nonempty('A listener/process record was printed.')] }),
    l({ title: 'Create a TCP state summary', focus: 'Grouping TCP connection objects by State creates a compact socket inventory.', example: 'Get-NetTCPConnection | Group-Object State', task: 'Print state=count rows for all TCP connections sorted by state.', solution: 'Get-NetTCPConnection | Group-Object State | Sort-Object Name | ForEach-Object { "$($_.Name)=$($_.Count)" }', checks: [nonempty('A TCP state summary was printed.')] }),
  ],
  'Test-Connection': [
    l({ title: 'Return a Boolean connectivity result', focus: '-Quiet returns True or False instead of probe objects.', example: 'Test-Connection localhost -Count 1 -Quiet', task: 'Test localhost once in quiet mode and print reachable=True.', solution: '"reachable=$(Test-Connection localhost -Count 1 -Quiet)"', checks: out('reachable=True') }),
    l({ title: 'Test the IPv4 loopback address', focus: 'Using 127.0.0.1 tests the IPv4 loopback path without depending on name resolution.', example: 'Test-Connection 127.0.0.1 -Count 1 -Quiet', task: 'Send one IPv4 loopback probe and print ipv4=True when it succeeds.', solution: '"ipv4=$(Test-Connection 127.0.0.1 -Count 1 -Quiet)"', checks: out('ipv4=True') }),
    l({ title: 'Inspect response-time data', focus: 'Windows PowerShell probe objects expose ResponseTime and address details for diagnostics.', example: 'Test-Connection localhost -Count 2 | Select ResponseTime', task: 'Send two localhost probes and print replies=2 nonnegative-latency=True.', solution: '$r=@(Test-Connection localhost -Count 2); "replies=$($r.Count) nonnegative-latency=$(@($r | Where-Object ResponseTime -lt 0).Count -eq 0)"', checks: out('replies=2 nonnegative-latency=True') }),
    l({ title: 'Build a target reachability report', focus: 'Quiet probes across a reviewed target list produce a concise Boolean preflight report.', example: '$targets | ForEach-Object { "$($_)=$(Test-Connection $_ -Quiet -Count 1)" }', task: 'Read targets.txt and print localhost=True and 127.0.0.1=True.', solution: 'Get-Content targets.txt | ForEach-Object { "$_=$(Test-Connection $_ -Count 1 -Quiet)" }', files: { 'targets.txt': 'localhost\n127.0.0.1\n' }, checks: out('localhost=True\n127.0.0.1=True') }),
  ],
  'Resolve-DnsName': [
    l({ title: 'Request an A record', focus: '-Type A limits resolution to IPv4 address records.', example: 'Resolve-DnsName localhost -Type A', task: 'Resolve localhost as type A and print at least one IPv4 address.', solution: 'Resolve-DnsName localhost -Type A | Select-Object -ExpandProperty IPAddress', checks: [contains('127.0.0.1')] }),
    l({ title: 'Use DNS-only mode with fallback', focus: '-DnsOnly avoids LLMNR and NetBIOS; localhost may instead require the hosts file, so the workflow reports that distinction.', example: 'Resolve-DnsName name -DnsOnly -ErrorAction SilentlyContinue', task: 'Attempt DNS-only resolution of localhost and print dns-records=<nonnegative-count>.', solution: '"dns-records=$(@(Resolve-DnsName localhost -DnsOnly -ErrorAction SilentlyContinue).Count)"', checks: [contains('dns-records=')] }),
    l({ title: 'Inspect record types', focus: 'Grouping response records by Type reveals which DNS data was returned.', example: 'Resolve-DnsName name | Group-Object Type', task: 'Resolve localhost and print type=count rows sorted by type.', solution: 'Resolve-DnsName localhost | Group-Object Type | Sort-Object Name | ForEach-Object { "$($_.Name)=$($_.Count)" }', checks: [nonempty('A DNS record-type summary was printed.')] }),
    l({ title: 'Create a local resolution report', focus: 'Resolving a target manifest and flattening addresses creates a useful preflight record.', example: '$names | ForEach-Object { Resolve-DnsName $_ ... }', task: 'Resolve localhost and print localhost=<comma-separated-addresses>, using unique sorted IP addresses.', solution: '$ips=Resolve-DnsName localhost | Where-Object IPAddress | Select-Object -ExpandProperty IPAddress | Sort-Object -Unique; "localhost=$($ips -join \',\')"', checks: [contains('localhost='), contains('127.0.0.1')] }),
  ],
  'Get-ExecutionPolicy': [
    l({ title: 'Inspect a specific scope', focus: '-Scope reveals the policy configured at one precedence level.', example: 'Get-ExecutionPolicy -Scope CurrentUser', task: 'Print process=<policy> for Process scope.', solution: '"process=$(Get-ExecutionPolicy -Scope Process)"', checks: [contains('process=')] }),
    l({ title: 'List every policy scope', focus: '-List displays scope precedence from machine policy through local machine.', example: 'Get-ExecutionPolicy -List', task: 'Print scope=policy for every execution-policy scope.', solution: 'Get-ExecutionPolicy -List | ForEach-Object { "$($_.Scope)=$($_.ExecutionPolicy)" }', checks: [contains('MachinePolicy='), contains('Process='), contains('LocalMachine=')] }),
    l({ title: 'Compare effective and process policies', focus: 'The effective policy can differ from a single scope due to precedence rules.', example: 'Get-ExecutionPolicy; Get-ExecutionPolicy -Scope Process', task: 'Print effective=<policy> process=<policy>.', solution: '"effective=$(Get-ExecutionPolicy) process=$(Get-ExecutionPolicy -Scope Process)"', checks: [contains('effective='), contains(' process=')] }),
    l({ title: 'Create an execution-policy audit', focus: 'A scope matrix plus effective policy creates a compact, read-only script-execution audit.', example: '$effective=Get-ExecutionPolicy; $scopes=Get-ExecutionPolicy -List', task: 'Print effective=<policy> followed by non-Undefined scope=policy rows sorted by scope.', solution: '"effective=$(Get-ExecutionPolicy)"; Get-ExecutionPolicy -List | Where-Object ExecutionPolicy -ne Undefined | Sort-Object Scope | ForEach-Object { "$($_.Scope)=$($_.ExecutionPolicy)" }', checks: [contains('effective=')] }),
  ],
  'Get-AuthenticodeSignature': [
    l({ title: 'Inspect an unsigned script', focus: 'Status distinguishes unsigned content from valid, invalid, unknown, and untrusted signatures.', example: 'Get-AuthenticodeSignature script.ps1 | Select Status', task: 'Print status=NotSigned for unsigned.ps1.', solution: '$s=Get-AuthenticodeSignature unsigned.ps1; "status=$($s.Status)"', files: { 'unsigned.ps1': 'Write-Output ready' }, checks: out('status=NotSigned') }),
    l({ title: 'Read signature status details', focus: 'StatusMessage explains the result in human-readable terms.', example: '$s=Get-AuthenticodeSignature script.ps1; $s.StatusMessage', task: 'Print status=<value> message-present=True for note.ps1.', solution: '$s=Get-AuthenticodeSignature note.ps1; "status=$($s.Status) message-present=$(-not [string]::IsNullOrWhiteSpace($s.StatusMessage))"', files: { 'note.ps1': '1+1' }, checks: [contains('status=NotSigned'), contains('message-present=True')] }),
    l({ title: 'Inspect several script signatures', focus: 'Get-AuthenticodeSignature accepts file objects through the pipeline for a reviewed script set.', example: 'Get-ChildItem *.ps1 | Get-AuthenticodeSignature', task: 'Print filename=NotSigned for a.ps1 and b.ps1 sorted by filename.', solution: 'Get-ChildItem *.ps1 | Get-AuthenticodeSignature | Sort-Object Path | ForEach-Object { "$([IO.Path]::GetFileName($_.Path))=$($_.Status)" }', files: { 'a.ps1': '1', 'b.ps1': '2' }, checks: out('a.ps1=NotSigned\nb.ps1=NotSigned') }),
    l({ title: 'Create a script-signature audit', focus: 'A recursive signature inventory identifies which scripts require signing before distribution.', example: 'Get-ChildItem scripts -Recurse *.ps1 | Get-AuthenticodeSignature', task: 'Recursively audit scripts and print signed=0 unsigned=3.', solution: '$s=@(Get-ChildItem scripts -Recurse -File -Filter *.ps1 | Get-AuthenticodeSignature); "signed=$(@($s | Where-Object Status -eq Valid).Count) unsigned=$(@($s | Where-Object Status -eq NotSigned).Count)"', files: { 'scripts/a.ps1': '1', 'scripts/lib/b.ps1': '2', 'scripts/lib/c.ps1': '3' }, checks: out('signed=0 unsigned=3') }),
  ],
  'Set-Acl': [
    l({ title: 'Copy an ACL to several files', focus: 'A reviewed ACL object can be applied consistently to multiple target paths.', example: '$acl=Get-Acl reference; targets | Set-Acl -AclObject $acl', task: 'Apply reference.txt ACL to a.txt and b.txt, then print applied=2.', solution: '$acl=Get-Acl reference.txt; Set-Acl a.txt,b.txt -AclObject $acl; "applied=2"', files: { 'reference.txt': '', 'a.txt': '', 'b.txt': '' }, checks: out('applied=2') }),
    l({ title: 'Apply an ACL through the pipeline', focus: 'Target paths can flow to Set-Acl while -AclObject supplies the reviewed descriptor.', example: 'Get-ChildItem targets | Set-Acl -AclObject $acl', task: 'Pipe every .txt file under targets to Set-Acl using reference.txt, then print targets=2.', solution: '$acl=Get-Acl reference.txt; $targets=@(Get-ChildItem targets -File -Filter *.txt); $targets | Set-Acl -AclObject $acl; "targets=$($targets.Count)"', files: { 'reference.txt': '', 'targets/a.txt': '', 'targets/b.txt': '', 'targets/keep.log': '' }, checks: out('targets=2') }),
    l({ title: 'Protect copied access rules', focus: 'SetAccessRuleProtection modifies a copied descriptor in memory before Set-Acl applies it to a disposable target.', example: '$acl=Get-Acl path; $acl.SetAccessRuleProtection($true,$true); Set-Acl target $acl', task: 'Protect target.txt access rules while preserving inherited rules, apply the ACL, and print protected=True.', solution: '$acl=Get-Acl target.txt; $acl.SetAccessRuleProtection($true,$true); Set-Acl target.txt $acl; "protected=$((Get-Acl target.txt).AreAccessRulesProtected)"', files: { 'target.txt': '' }, checks: out('protected=True') }),
    l({ title: 'Apply and verify a permission template', focus: 'A practical ACL workflow applies one reviewed template and compares normalized SDDL afterward.', example: '$acl=Get-Acl template; Set-Acl targets -AclObject $acl; compare Sddl', task: 'Apply template.txt ACL to target.txt and print acl-match=True when their SDDL descriptors match.', solution: '$acl=Get-Acl template.txt; Set-Acl target.txt -AclObject $acl; "acl-match=$((Get-Acl template.txt).Sddl -eq (Get-Acl target.txt).Sddl)"', files: { 'template.txt': '', 'target.txt': '' }, checks: out('acl-match=True') }),
  ],
};
